Allow locateFile to be specified directly
tensorflow/tfjs-models pull request #1039
Opened 2022-08-16 16:25 UTC by satoren

2022-09-06 19:15 UTC, ahmedsabie requested changes

2022-09-06 19:15 UTC, ahmedsabie commented on body-segmentation/src/selfie_segmentation_mediapipe/types.ts
> +  locateFile?: (path: string, base: string) => string;
Please add a comment to the interface describing this option, and similarly in README.md in the same folder as this file.

2022-09-06 19:15 UTC, ahmedsabie commented
Also there is a lint error: `body-segmentation/src/selfie_segmentation_mediapipe/segmenter.ts[74, 6]: Missing semicolon`

2022-09-07 18:18 UTC, ahmedsabie reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1039)* status: 0 of 1 approvals obtained (waiting on @satoren)



<!-- Sent from Reviewable.io -->

2022-09-07 18:19 UTC, ahmedsabie approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1039)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-13 20:12 UTC, lina128 reviewed
Hi thank you for your contribution @satoren , just want to understand your use case better. Why the existing solutionPath argument can't fulfill your use case?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1039#-:-NBsT_M4-PG8CNWSvJz9:biw4spr)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-14 07:21 UTC, satoren commented
Hi thank you for the review,  I'm using [vite](https://vitejs.dev/) for Bundler, but when I import a script with vite, the actual file name contains a hash, so I cannot use it in the solutionPath. Therefore, I had to copy the file to the asset directory manually or automatically (e.g., with a plugin). Also, if the file is copied to the asset directory in that way, the file name does not change between versions, so the old version may be referenced when the cache is set.

2022-09-15 20:12 UTC, lina128 approved these changes
Got it, fair enough. LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1039#-:-NC1lwzpEVEA_eTCVbcX:buit5fe)* status: :shipit: complete! 2 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-15 20:27 UTC, merged