[pose-detection] Add WebGPU backend
tensorflow/tfjs-models pull request #1044
Opened 2022-10-21 15:57 UTC by haoyunfeix

1. Add tfjs-webgpu backend
2. Update tfjs to 4.0.0
3. Fix backend changing issue in upload_video demo
4. Add URL backend parameter

2022-10-27 08:16 UTC, haoyunfeix commented
@mattsoulanille @lina128 PTAL, Thanks.

2022-10-27 17:41 UTC, mattsoulanille requested changes
This looks good (working on Chrome Dev 108.0.5359.19 Linux), but I have a concern about surfacing errors to the user.

WebGPU is not supported on all devices, and right now, if the demo tries to switch to the WebGPU backend on an unsupported device, it freezes with no error message visible to the user. This is because the WebGPU backend [only registers itself it WebGPU is supported](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/src/base.ts#L25-L26), and in `util.js`, we [throw an error if a backend is not in the registry](https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/demos/live_video/src/util.js#L39-L41).

Can we catch this error in [`index.js`](https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/demos/live_video/src/index.js#L99-L101) and `alert()` the user that the backend is not supported? Ideally, we'd also switch back to the previous backend (both the tfjs runtime and the UI), but if this is difficult, then alerting the user should be sufficient.

I've discovered this issue on the live demo, but I think the upload video demo has it as well.

2022-10-31 07:23 UTC, haoyunfeix commented on pose-detection/demos/upload_video/src/index.js
> -  checkUpdate();
Thanks, removed.

2022-10-31 07:23 UTC, haoyunfeix commented on pose-detection/demos/upload_video/src/option_panel.js
> +  if(params.STATE.backend === undefined || params.STATE.backend === null) {
Thanks, that doc is helpful!

2022-10-31 18:35 UTC, mattsoulanille approved these changes
Thanks for adding the error message when WebGPU is not supported.

2022-10-31 18:35 UTC, mattsoulanille commented on pose-detection/demos/live_video/src/util.js
> +      alert(`${backendName} backend is not registered. Maybe should use a WebGPU enabled target e.g. chrome canary with --enable-unsafe-webgpu flag`);
```suggestion
      alert('webgpu backend is not registered. Your browser may not support WebGPU yet. To test this backend, please use a supported browser, e.g. Chrome canary with --enable-unsafe-webgpu flag');
```

2022-11-02 18:21 UTC, lina128 approved these changes
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/1044#-:-NFtZgah6Yi2mpXGBbzx:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @haoyunfeix and @mattsoulanille)



<!-- Sent from Reviewable.io -->

2022-11-02 18:22 UTC, merged