Set webgl and webgpu as external
tensorflow/tfjs-models pull request #1140
Opened 2023-03-28 05:32 UTC by axinging

2023-03-28 05:34 UTC, axinging commented
@mattsoulanille  @Linchenn  PTAL

@qjia7 @xhcao @gyagp

2023-03-28 05:58 UTC, Linchenn commented
Is this fixing the duplicated kernel registration problem?

2023-03-28 06:07 UTC, axinging commented
> Is this fixing the duplicated kernel registration problem?

Yes.

2023-03-28 06:14 UTC, qjia7 commented
> > Is this fixing the duplicated kernel registration problem?
> 
> Yes.

@axinging Can you also give a little explanations that why webgl doesn't complain those warnings, but webgpu does?

2023-03-28 06:19 UTC, axinging commented
> This change is [<img alt="Reviewable" height="34" src="https://camo.githubusercontent.com/a8b5f6726de4903e6ce89df24ad596326aa4f49974dbb99137f93e280f30421c/68747470733a2f2f72657669657761626c652e696f2f7265766965775f627574746f6e2e737667">](https://reviewable.io/reviews/tensorflow/tfjs-models/1140)



> > > Is this fixing the duplicated kernel registration problem?
> > 
> > 
> > Yes.
> 
> @axinging Can you also give a little explanations that why webgl doesn't complain those warnings, but webgpu does?

The production code will include code from other package when: package is imported(such as import * as tfwebgpu from '@tensorflow/tfjs-backend-webgpu';) and is non external in rollup.config.js. 
The webgl package is not imported in code, so it doesn't has this problem.

2023-03-28 06:25 UTC, qjia7 commented
> > This change is [<img alt="Reviewable" height="34" src="https://camo.githubusercontent.com/a8b5f6726de4903e6ce89df24ad596326aa4f49974dbb99137f93e280f30421c/68747470733a2f2f72657669657761626c652e696f2f7265766965775f627574746f6e2e737667">](https://reviewable.io/reviews/tensorflow/tfjs-models/1140)
> 
> > > > Is this fixing the duplicated kernel registration problem?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > @axinging Can you also give a little explanations that why webgl doesn't complain those warnings, but webgpu does?
> 
> The production code will include code from other package when: package is imported(such as import * as tfwebgpu from '@tensorflow/tfjs-backend-webgpu';) and is non external in rollup.config.js. The webgl package is not imported in code, so it doesn't has this problem.

Sounds good for me. Thanks.

2023-03-28 06:29 UTC, Linchenn approved these changes
Thanks for the explanation and fixing it! LGTM

2023-03-28 19:40 UTC, mattsoulanille requested changes
Looks good. Just one small change to make.

2023-03-29 01:24 UTC, axinging commented on pose-detection/rollup.config.js
> +      '@tensorflow/tfjs-backend-webgpu', '@tensorflow/tfjs-backend-webgl',
Done

2023-03-29 22:09 UTC, mattsoulanille approved these changes
LGTM

2023-03-29 22:09 UTC, merged