[facemesh] rename
tensorflow/tfjs-models pull request #526
Opened 2020-10-01 18:06 UTC by annxingyuan

2020-10-06 14:05 UTC, annxingyuan commented
Hey @pyu10055, @tafsiri - this PR contains the code you've already reviewed from https://github.com/tensorflow/tfjs-models/pull/508 - but under a new package name: `face-landmarks-detection`, which wraps `mediapipe-facemesh`. So the only thing to review is the new wrapper interface.

2020-10-06 14:16 UTC, luispuig commented
First, thanks for your effort :) 

Is https://storage.googleapis.com/tfjs-models/demos/facemesh/index.html  the link with the example running the last version? I am trying to check the performance improvement done in the las commits.

And probably unrelated to this, on iOS14 it gets frozen on the first frame.

2020-10-06 16:49 UTC, pyu10055 requested changes
Thank you Ann, looks like we will create a new NPM, what is the plan to sunset the original npm and is there way to redierct users to the new npm?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-:-MIynwj_-8nGAj5cWwo5:bavkkrz)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[face-landmarks-detection/README.md, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyLy1R1nJ4Ve5e8oi5:-MIyLy1R1nJ4Ve5e8oi6:bxjbi82) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L28)):*
> ```Markdown
> ```html
> <!-- Require the peer dependencies of face-landmarks-detection. -->
> <script src="https://unpkg.com/@tensorflow/tfjs-core@2.4.0/dist/tf-core.js"></script>
> ```

the script is locking the version number of each dep, but the npm instruction is not, it would be better to be consistent.
___
*[face-landmarks-detection/README.md, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyjVvA5VOt8dE6Yrlo:-MIyjVvA5VOt8dE6Yrlp:bcq7zeb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L68)):*
> ```Markdown
> async function main() {
>   // Load the MediaPipe Facemesh package.
>   const model = await faceLandmarksDetection.load('mediapipe-facemesh');
> ```

Will it be better to have a enum for model source than the plain string?
___
*[face-landmarks-detection/README.md, line 70 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyjp-pC9kkwVX-kYba:-MIyjp-pC9kkwVX-kYbb:btgnzqz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L70)):*
> ```Markdown
>   const model = await faceLandmarksDetection.load('mediapipe-facemesh');
> 
>   // Pass in a video stream (or an image, canvas, or 3D tensor) to obtain an
> ```

for video stream you will only get a single prediction on the current frame, right? 
maybe good to explain that the users to reduce confusion.
___
*[face-landmarks-detection/README.md, line 141 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIykAr_B4xQ5MZXOPD0:-MIykAr_B4xQ5MZXOPD1:bvtj8sb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L141)):*
> ```Markdown
>   * **iouThreshold** - A float representing the threshold for deciding whether boxes overlap too much in non-maximum suppression. Must be between [0, 1]. Defaults to 0.3.
> 
>   * **scoreThreshold** - A threshold for deciding when to remove boxes based on score in non-maximum suppression. Defaults to 0.75.
> ```

clarify the range, in general it would be good to explain the effect of these params, for example for iouThreshold what does 0 or 1 mean in terms of the output.
___
*[face-landmarks-detection/demo/index.html, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIykqO-AsM9XKGJrCFc:-MIykqO-AsM9XKGJrCFd:b-gkha7x) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/demo/index.html#L34)):*
> ```HTML
>   /* center the canvas within its wrapper */
>   #scatter-gl-container canvas {
>     transform: translate3d(-50%, -50%, 0);
> ```

sort the attributes
___
*[face-landmarks-detection/src/index.ts, line 41 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIylVA_DQMSsgM-xtko:-MIylVA_DQMSsgM-xtkp:b-o9t5ny) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/src/index.ts#L41)):*
> ```XML
>  * Defaults to true.
>  */
> export async function load(
> ```

should we support custom url as part of the config param similar to other models?
___
*[face-landmarks-detection/src/version.ts, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyljo_4AJjYB2ZtHaA:-MIyljo_4AJjYB2ZtHaB:b-sy1ykt) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/src/version.ts#L4)):*
> ```XML
> 
> // This code is auto-generated, do not modify this file!
> const version = '0.0.4';
> ```

this version seems to be out-dated


<!-- Sent from Reviewable.io -->

2020-10-07 01:40 UTC, mhogg commented
Hi,

Trying to run this branch to test fixes related to issue #508. I haven't had any issues running any of the other examples, but when I try to run face-landmarks-detection, I get the following error below. Not sure sure if this is related to https://github.com/tensorflow/tfjs/issues/1447 or not.

```
Uncaught (in promise) Error: Found more than one (2) load handlers for URL 'https://tfhub.dev/mediapipe/tfjs-model/facemesh/1/default/1/model.json?tfjs-format=file'
    at GraphModel.findIOHandler (graph_model.ts:99)
    at GraphModel.load (graph_model.ts:112)
    at Object.loadGraphModel (graph_model.ts:398)
    at index.ts:115
    at step (index.ts:16)
    at Object.next (index.ts:16)
    at index.ts:16
    at new Promise (<anonymous>)
    at __awaiter (index.ts:16)
    at loadMeshModel (index.ts:114)
```

2020-10-07 06:05 UTC, psw7420 commented
how to run demo https://storage.googleapis.com/tfjs-models/demos/facemesh/index.html on my server?
even downloaded from this github, there is no iris data on demo program.

2020-10-07 13:37 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[face-landmarks-detection/README.md, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyLy1R1nJ4Ve5e8oi5:-MJ25oEA-ldBjrkTXRCu:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L28)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

the script is locking the version number of each dep, but the npm instruction is not, it would be better to be consistent.
</blockquote></details>

Done
___
*[face-landmarks-detection/README.md, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyjVvA5VOt8dE6Yrlo:-MJ26lUc9XMhXu6rcQtl:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L68)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Will it be better to have a enum for model source than the plain string?
</blockquote></details>

Done
___
*[face-landmarks-detection/README.md, line 70 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyjp-pC9kkwVX-kYba:-MJ27FXjE9LvbNj25sBO:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L70)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

for video stream you will only get a single prediction on the current frame, right? 
maybe good to explain that the users to reduce confusion.
</blockquote></details>

Done
___
*[face-landmarks-detection/README.md, line 141 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIykAr_B4xQ5MZXOPD0:-MJ2Ad2A1Q_RnmuqZP_r:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L141)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

clarify the range, in general it would be good to explain the effect of these params, for example for iouThreshold what does 0 or 1 mean in terms of the output.
</blockquote></details>

Done
___
*[face-landmarks-detection/demo/index.html, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIykqO-AsM9XKGJrCFc:-MJ2B0k01t1RvzB2bjZm:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/demo/index.html#L34)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

sort the attributes
</blockquote></details>

Done
___
*[face-landmarks-detection/src/index.ts, line 41 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIylVA_DQMSsgM-xtko:-MJ2GrEP3JuBQf9zpzw4:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/src/index.ts#L41)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we support custom url as part of the config param similar to other models?
</blockquote></details>

Done
___
*[face-landmarks-detection/src/version.ts, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyljo_4AJjYB2ZtHaA:-MJ2CTYi8B3qVOBZKM4F:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/src/version.ts#L4)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this version seems to be out-dated
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-10-07 13:38 UTC, annxingyuan commented
Hi @pyu10055 - thanks for taking a look. I've talked with @tafsiri about the best way for sunsetting the existing facemesh repo - we were thinking we would add a notice at the top of the facemesh README (included in this PR) that informs users that the package has been renamed, and that future updates will be in face-landmarks-detection. 

We thought about deprecating facemesh but decided that it wouldn't hurt to keep it around, as long as we were very explicit in the README about our plans.

What do you think?

2020-10-07 17:01 UTC, pyu10055 requested changes
sounds good, is it possible to have an extra release on the previous npm to show some warning messages?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-:-MJ3-SuaDjCgBYqGMvic:b-qlo4xc)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[face-landmarks-detection/README.md, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyjVvA5VOt8dE6Yrlo:-MJ2w4UfDb4eKjaZD5i4:b3zj3gz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L68)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Done
</blockquote></details>

thanks, please update the example code here.
___
*[face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts, line 76 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJ3-H6A5okLmmCDdbUf:-MJ3-H6BAmYVzRrsvG-h:b44sx1l) ([raw file](https://github.com/tensorflow/tfjs-models/blob/159b79e55521e33f8bb07dde4dc2e89dfc0e9214/face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts#L76)):*
> ```XML
>     // from memory test.
>     await model.estimateFaces(
>         input, false /* return tensors */, false /* return tensors */,
> ```

flipHorizontal?
___
*[face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts, line 77 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJ3-KbNCxk93NTCDX0H:-MJ3-KbNCxk93NTCDX0I:bl153cf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/159b79e55521e33f8bb07dde4dc2e89dfc0e9214/face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts#L77)):*
> ```XML
>     await model.estimateFaces(
>         input, false /* return tensors */, false /* return tensors */,
>         true /* predict irises */);
> ```

This parameter is not part of the signature in the interface 


<!-- Sent from Reviewable.io -->

2020-10-07 17:15 UTC, annxingyuan reviewed
Yes, I've updated the facemesh version number and will publish a new release so the NPM landing page will include the warning.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-:-MJ305MD8nEjvZKE4V0Y:bnvbm03)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[face-landmarks-detection/README.md, line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MIyjVvA5VOt8dE6Yrlo:-MJ322bJ1lX7ivzYdTC6:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/9eeeae4b358d81547a47ccca1aa0f56934bd0b24/face-landmarks-detection/README.md#L68)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

thanks, please update the example code here.
</blockquote></details>

Done
___
*[face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts, line 76 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJ3-H6A5okLmmCDdbUf:-MJ32NI_ALtIQA-tzeq2:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/159b79e55521e33f8bb07dde4dc2e89dfc0e9214/face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts#L76)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

flipHorizontal?
</blockquote></details>

Done
___
*[face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts, line 77 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJ3-KbNCxk93NTCDX0H:-MJ32YeSDzLpJQTwPMrN:bgqfu2e) ([raw file](https://github.com/tensorflow/tfjs-models/blob/159b79e55521e33f8bb07dde4dc2e89dfc0e9214/face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts#L77)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

This parameter is not part of the signature in the interface 
</blockquote></details>

It is part of the mediaPipe interface signature, which inherits from the top level face landmarks interface signature. It feels like the iris detection parameter is a mediapipe-specific thing. Does that make sense?


<!-- Sent from Reviewable.io -->

2020-10-08 05:20 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts, line 77 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJ3-KbNCxk93NTCDX0H:-MJ5dWLa2YtYAJG1oe9G:b42j761) ([raw file](https://github.com/tensorflow/tfjs-models/blob/159b79e55521e33f8bb07dde4dc2e89dfc0e9214/face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts#L77)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

It is part of the mediaPipe interface signature, which inherits from the top level face landmarks interface signature. It feels like the iris detection parameter is a mediapipe-specific thing. Does that make sense?
</blockquote></details>

The concern is the param list here is different from the interface. Do you know make sense to have an modelOptions param that can be customized for different supported packages?


<!-- Sent from Reviewable.io -->

2020-10-08 11:29 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts, line 77 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJ3-KbNCxk93NTCDX0H:-MJ6yDigEYuEaFNBwLrJ:bj2x0os) ([raw file](https://github.com/tensorflow/tfjs-models/blob/159b79e55521e33f8bb07dde4dc2e89dfc0e9214/face-landmarks-detection/src/mediapipe-facemesh/face-landmarks-detection_test.ts#L77)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

The concern is the param list here is different from the interface. Do you know make sense to have an modelOptions param that can be customized for different supported packages?
</blockquote></details>

That sounds good - let me know if this is what you had in mind.


<!-- Sent from Reviewable.io -->

2020-10-09 16:01 UTC, pyu10055 approved these changes
> Reviewed 20 of 32 files at r1, 1 of 1 files at r2, 4 of 7 files at r3, 1 of 2 files at r4, 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[face-landmarks-detection/src/index.ts, line 30 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJD2jLf6Dyl-AqtYGmm:-MJD2jLf6Dyl-AqtYGmn:b-rtpvcq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a4a6e08882945f4e5087d77d46a6078703343eab/face-landmarks-detection/src/index.ts#L30)):*
> ```XML
>  * Load the package.
>  *
>  * @param options - a configuration object with the following properties:
> ```

rename to config, also missing pkg param
___
*[face-landmarks-detection/src/types.ts, line 24 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJD4DftCmuPJweqgcwO:-MJD4DftCmuPJweqgcwP:boiqvw1) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a4a6e08882945f4e5087d77d46a6078703343eab/face-landmarks-detection/src/types.ts#L24)):*
> ```XML
> export interface FaceLandmarksPrediction {
>   /** Facial landmark coordinates. */
>   mesh: tf.Tensor2D|Array<[number, number]>|Array<[number, number, number]>;
> ```

should it allow Tensor3D?
___
*[face-landmarks-detection/src/mediapipe-facemesh/test_util.ts, line 18 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJD4vgZESWw52iAXja2:-MJD4vgZESWw52iAXja3:b-24rs9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a4a6e08882945f4e5087d77d46a6078703343eab/face-landmarks-detection/src/mediapipe-facemesh/test_util.ts#L18)):*
> ```XML
>  */
> 
> export const stubbedImageVals = [178,179,183,151,152,156,121,122,126,106,107,111,63,62,67,5,4,9,17,17,19,13,13,15,19,19,21,13,13,15,18,16,17,23,21,22,20,18,19,15,13,14,16,15,13,19,15,12,33,23,21,54,43,39,56,43,37,63,50,44,83,68,61,55,40,33,58,41,33,77,60,52,56,39,31,52,35,27,61,44,36,60,43,35,53,36,28,69,52,44,78,63,56,62,48,39,30,11,4,48,31,23,57,42,37,46,35,31,38,26,26,39,29,27,46,32,29,47,32,25,40,20,11,57,35,22,50,26,14,60,38,25,85,67,57,56,41,34,30,19,17,63,55,53,40,31,32,12,4,2,16,6,4,20,7,1,21,6,0,18,1,0,26,9,1,24,10,1,28,13,8,32,19,13,37,26,22,27,16,12,18,7,1,28,17,11,36,21,14,47,32,25,34,20,11,39,25,16,48,31,21,20,3,0,62,42,31,58,38,27,68,44,32,73,49,37,73,47,34,80,54,41,65,37,25,51,23,11,56,26,16,70,40,30,84,54,44,78,51,40,70,47,39,44,26,16,55,38,30,63,46,38,60,45,38,22,7,0,26,13,7,31,18,12,22,9,3,23,10,4,38,23,16,29,15,6,58,39,32,70,52,42,68,48,37,84,70,61,65,60,57,82,82,82,77,77,79,72,72,74,63,64,69,59,60,65,47,50,57,58,61,68,56,56,64,56,56,64,55,56,61,55,56,61,56,55,60,57,57,59,59,57,60,59,57,58,58,57,62,57,56,61,56,55,60,55,54,59,55,54,59,55,54,59,55,54,59,55,54,59,54,53,58,53,52,57,53,52,57,54,53,58,55,54,59,55,54,59,54,53,58,54,53,58,193,194,198,162,163,167,127,128,132,114,115,119,81,80,85,25,24,29,15,15,17,12,12,14,11,11,13,23,23,23,16,14,15,10,8,9,22,20,21,19,18,16,14,13,11,30,25,22,29,19,17,29,18,12,65,52,46,84,71,63,74,59,52,27,13,4,56,39,31,54,37,29,45,28,20,60,43,35,73,56,48,68,51,43,67,50,42,82,65,57,61,46,39,11,0,0,64,47,39,57,40,32,46,31,26,38,27,25,39,29,28,46,36,34,51,40,36,56,41,34,61,41,32,65,43,32,59,35,23,71,49,36,71,53,43,50,35,28,45,34,32,44,34,33,32,23,24,15,7,5,14,3,1,15,2,0,15,0,0,18,1,0,28,11,3,32,18,9,36,21,16,30,17,11,33,22,18,42,31,27,33,22,16,16,5,0,53,38,31,34,19,12,25,11,2,47,30,20,42,25,15,61,43,31,67,47,36,64,42,29,77,53,41,76,52,40,82,56,43,59,33,20,50,22,10,67,39,27,76,46,36,75,45,35,80,50,40,72,45,34,54,32,21,36,18,8,59,40,33,47,30,22,56,41,34,38,23,16,18,5,0,29,16,10,12,0,0,36,23,15,32,17,10,43,26,18,55,37,27,68,50,38,70,50,39,85,68,60,86,81,77,70,70,70,75,75,75,86,86,88,70,69,74,57,58,63,55,56,61,56,56,64,55,55,63,56,56,64,57,58,63,58,59,64,59,58,63,58,57,62,58,56,59,57,55,58,57,56,61,57,56,61,56,55,60,55,54,59,55,54,59,54,53,58,55,54,59,55,54,59,54,53,58,54,53,58,53,52,57,53,52,57,54,53,58,54,53,58,53,52,57,52,51,56,199,202,207,171,174,179,134,137,142,120,123,128,96,97,101,44,45,49,8,8,10,13,13,15,16,14,15,20,18,19,24,20,21,21,17,16,19,15,14,26,22,21,29,25,24,27,19,16,38,27,23,51,38,32,72,57,52,78,63,56,63,46,39,35,18,10,55,36,29,46,28,18,36,18,8,47,29,19,44,27,19,60,43,35,81,66,59,60,45,38,41,26,19,65,50,43,70,53,46,50,35,28,36,22,19,39,28,26,45,35,34,46,36,34,45,34,30,50,35,30,62,43,36,58,38,27,69,47,34,94,74,63,75,57,47,50,35,28,49,38,34,13,3,1,22,14,12,22,14,11,16,5,1,15,2,0,15,0,0,27,10,2,39,22,14,51,37,28,43,28,23,40,27,21,33,22,18,51,40,36,47,36,32,26,15,9,53,38,31,25,10,3,40,23,15,58,40,30,54,36,26,81,61,50,69,47,36,74,50,38,86,62,50,80,54,41,76,48,36,80,52,40,70,42,30,78,50,38,95,67,55,88,60,48,76,48,37,70,43,32,35,13,2,34,16,4,53,35,25,37,20,12,53,38,31,42,27,20,17,4,0,20,7,1,24,9,2,15,0,0,52,35,28,71,54,46,73,55,45,63,43,32,75,53,42,72,55,45,70,63,57,80,79,77,87,86,84,79,79,79,78,78,80,65,64,69,57,56,62,54,55,60,55,56,61,56,57,62,57,58,63,57,58,63,58,57,62,57,56,61,57,57,59,56,56,58,56,55,60,56,55,60,55,54,59,55,54,59,54,53,58,54,53,58,54,53,58,54,53,58,54,53,58,54,53,58,53,52,57,53,52,57,53,52,57,52,51,56,51,50,55,50,49,54,198,201,206,178,181,186,145,148,153,127,130,135,105,106,111,60,61,65,6,6,8,17,17,19,14,12,13,8,7,5,19,15,14,25,21,20,23,19,18,39,34,31,53,48,45,47,37,35,82,69,63,91,76,69,80,65,58,77,60,52,52,35,27,53,36,26,35,17,7,31,13,3,34,16,6,41,23,13,62,45,37,69,52,44,55,40,33,62,47,40,75,60,53,70,55,48,33,18,11,27,12,7,28,17,15,38,28,26,43,35,33,40,30,28,41,30,28,50,35,30,64,45,38,64,44,35,81,59,48,92,72,61,61,42,35,35,20,13,35,24,20,17,7,5,14,4,3,33,23,21,26,12,9,25,10,3,28,11,3,43,26,18,55,38,30,71,57,48,46,31,26,56,43,37,42,31,27,54,43,39,52,41,37,47,36,32,32,19,13,30,15,8,56,38,28,63,43,32,78,58,47,70,48,35,73,49,37,84,60,48,87,61,48,75,49,36,74,46,34,82,54,42,91,63,51,89,61,49,74,46,34,73,47,34,73,45,34,41,14,3,28,6,0,37,19,7,41,23,13,43,26,18,49,34,27,28,13,6,25,12,6,12,0,0,20,5,0,25,10,3,59,42,34,57,39,29,94,74,63,85,66,52,50,28,15,80,62,52,45,36,29,76,73,68,91,87,84,74,73,71,81,79,80,68,66,69,57,56,61,55,54,60,57,56,62,56,57,62,55,56,61,54,55,60,55,54,59,56,55,60,57,57,59,58,58,60,55,54,59,55,54,59,55,54,59,54,53,58,54,53,58,54,53,58,54,53,58,54,53,58,54,53,58,53,52,57,52,51,56,52,51,56,52,51,56,52,51,56,51,50,55,49,48,53,200,205,211,185,190,196,155,160,166,132,137,141,113,116,121,78,79,83,17,17,19,18,18,20,18,16,17,21,17,16,17,11,11,21,16,13,36,31,28,48,40,37,55,47,44,67,56,52,87,72,65,78,61,53,85,68,60,88,70,60,56,38,28,60,42,32,27,7,0,33,13,2,55,37,27,69,51,41,78,61,53,67,50,42,61,46,39,85,70,63,79,66,60,37,24,18,35,22,16,36,25,21,42,31,29,43,33,32,39,31,29,38,28,26,47,36,34,60,47,41,61,44,37,79,61,51,93,73,64,73,53,44,48,29,22,31,16,9,16,2,0,21,12,7,8,0,0,39,30,25,33,20,14,34,19,12,41,24,16,56,38,28,66,49,41,78,64,55,50,35,30,58,45,39,57,46,42,65,55,53,51,40,36,37,26,22,32,19,13,46,31,24,59,41,31,71,49,38,85,63,52,68,44,32,80,56,44,81,55,42,81,53,41,75,47,35,79,51,39,92,64,52,81,55,42,77,51,38,75,48,37,49,25,13,34,7,0,32,8,0,32,12,3,30,12,2,40,21,14,54,37,29,41,26,19,18,3,0,28,15,9,14,1,0,17,2,0,39,24,17,38,21,13,37,19,9,51,31,20,102,80,67,59,35,23,71,51,40,56,46,37,43,36,28,64,57,51,80,75,71,84,78,78,64,60,61,61,59,62,55,54,59,55,54,59,55,54,59,55,54,60,55,54,60,56,55,60,56,55,60,56,56,58,56,56,58,54,53,58,54,53,58,54,53,58,54,53,58,54,53,58,54,53,58,53,52,57,53,52,57,52,51,56,51,50,55,51,50,55,51,50,55,52,51,56,52,51,56,51,50,55,50,49,54,203,208,214,190,195,201,164,169,175,135,140,146,120,123,128,93,97,100,37,36,41,12,12,12,23,19,20,20,16,15,29,24,21,41,33,30,44,36,33,50,41,36,57,48,43,60,47,41,47,30,22,64,46,36,88,70,60,71,53,43,66,48,38,59,41,31,35,15,4,58,38,27,83,65,55,74,56,46,53,36,28,68,51,43,92,77,70,63,50,42,30,17,11,43,32,28,37,26,22,40,30,28,43,33,32,39,29,28,33,25,23,37,27,25,49,38,36,62,49,43,65,48,41,80,61,54,80,61,54,47,28,21,51,34,27,55,40,33,17,4,0,8,0,0,8,0,0,40,29,25,39,24,19,42,25,17,52,33,26,62,44,34,73,56,48,76,61,54,57,42,37,44,33,29,69,58,56,78,68,66,51,40,36,10,0,0,56,43,37,61,46,39,76,56,47,89,67,56,71 [...]

2020-10-12 12:37 UTC, annxingyuan reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/526)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[face-landmarks-detection/src/index.ts, line 30 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJD2jLf6Dyl-AqtYGmm:-MJRmh8WBe3x8LjWJaW5:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a4a6e08882945f4e5087d77d46a6078703343eab/face-landmarks-detection/src/index.ts#L30)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

rename to config, also missing pkg param
</blockquote></details>

Done
___
*[face-landmarks-detection/src/types.ts, line 24 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJD4DftCmuPJweqgcwO:-MJRn2ee-Fll2T8Qh6T1:bia93za) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a4a6e08882945f4e5087d77d46a6078703343eab/face-landmarks-detection/src/types.ts#L24)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should it allow Tensor3D?
</blockquote></details>

I don't think so - the shape of the mesh tensor is either [468, 3] or [478, 3]. 
___
*[face-landmarks-detection/src/mediapipe-facemesh/test_util.ts, line 18 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/526#-MJD4vgZESWw52iAXja2:-MJRo6xk6_QsH_kWxB5J:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/a4a6e08882945f4e5087d77d46a6078703343eab/face-landmarks-detection/src/mediapipe-facemesh/test_util.ts#L18)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

there is some special characters at the end.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-10-12 13:06 UTC, merged

2020-10-12 13:08 UTC, annxingyuan commented
Hi @mhogg @psw7420 - sorry for my delayed response. It's a little bit tricky to test local packages that haven't been published to NPM yet. Now that face-landmarks-detection has been published (as of 10 minutes ago), the demo should work out of the box!

2020-10-12 14:08 UTC, denkerinteraktivgmbh commented
Hi @annxingyuan,

we just testet the new NPM package...

```
await this.model.estimateFaces({
            input: this.video,
            returnTensors: false,
            flipHorizontal: true,
            predictIrises : false
        });
```
results in an error:

> Argument of type '{ input: HTMLVideoElement; returnTensors: false; flipHorizontal: true; predictIrises: boolean; }' is not assignable to parameter of type 'EstimateFacesConfig'.
>   Object literal may only specify known properties, and 'predictIrises' does not exist in type 'EstimateFacesConfig'.

2020-10-12 14:19 UTC, annxingyuan commented
Thanks for pointing this out @denkerinteraktivgmbh ! I will fix this soon.

2020-10-12 23:10 UTC, radames commented on face-landmarks-detection/demo/index.js
> +          return BLUE;
Hi,
Thanks for this new cool model! I was testing it here https://observablehq.com/d/a4b086b09d93a22b

Considering the flatted array is always in order, you can do this to set the Iris colors for the scatter plot points for multiple faces. You can see it live [here](https://observablehq.com/d/a4b086b09d93a22b), it's just a detail but at least the faces won't show red.

~~~js
        if (i % (NUM_KEYPOINTS + NUM_IRIS_KEYPOINTS * 2) > NUM_KEYPOINTS) {
          return RED;
        }
        return BLACK;
~~~