[pose-detection]Initial blazepose checkin.
tensorflow/tfjs-models pull request #616
Opened 2021-03-23 03:59 UTC by lina128

2021-03-24 22:32 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @mhays-google)

___
*[pose-detection/demo/src/camera.js, line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaDXCLEbO1qZ-2YxHE:-MWaDXCLEbO1qZ-2YxHF:b-r9r9ou) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/camera.js#L99)):*
> ```JavaScript
>    * Draw the keypoints on the video.
>    * @param keypoints A list of keypoints, may be normalized.
>    * @param scale If the keypoints are normalized, need to pass in the video
> ```

shouldScale
___
*[pose-detection/demo/src/index.js, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaEQaEEWRMYimtbv3v:-MWaEQaEEWRMYimtbv3w:b-5m4w6j) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/index.js#L33)):*
> ```JavaScript
>   switch (model) {
>     case posedetection.SupportedModels.PoseNet:
>       detector = await posedetection.createDetector(STATE.model.model, {
> ```

should this be just `model` instead of `STATE.model.model`? same for the mediapipe case
___
*[pose-detection/demo/src/index.js, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaFtC27F2yO5fc7n5o:-MWaFtC27F2yO5fc7n5p:b1opwgb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/index.js#L67)):*
> ```JavaScript
>     STATE.changeToModel = null;
> 
>     await createDetector(STATE.model.model);
> ```

should the created model be cached? 
Also, if it is not cached,  there should be model dispose step?
___
*[pose-detection/demo/src/index.js, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaErHr51tTwWLWJiKY:-MWaErHr51tTwWLWJiKZ:bvaqmxx) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/index.js#L84)):*
> ```
>  camera.drawResult(poses[0]);
> ```
will  ````
const shouldScale = STATE.model.model === posedetection.SupportedModels.MediapipeBlazepose;
camera.drawResult(poses[0],  shouldScale);
``` 
be cleaner? 
```

___
*[pose-detection/src/create_detector.ts, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaGsvP51ZrQSqdh4pM:-MWaGsvP51ZrQSqdh4pN:bf6ystu) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/create_detector.ts#L38)):*
> ```XML
>       return PosenetDetector.load(modelConfig as PosenetModelConfig);
>     case SupportedModels.MediapipeBlazepose:
>       return BlazeposeDetector.load(modelConfig);
> ```

does this need to be casted to `BlazeposeModelConfig`?
___
*[pose-detection/src/blazepose/blazepose_test.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaHFAhC-1dsDjwL9lF:-MWaHFAhC-1dsDjwL9lG:b-u7xkgv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/blazepose_test.ts#L24)):*
> ```XML
> import * as poseDetection from '../index';
> 
> describeWithFlags('Blazepose', ALL_ENVS, () => {
> ```

you may want to add a test for checking memory leak after model is disposed.
___
*[pose-detection/src/blazepose/detector.ts, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaL0ugBO8umj_ZTDB2:-MWaL0ugBO8umj_ZTDB3:b60t2tn) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L53)):*
> ```XML
>  * Blazepose detector class.
>  */
> export class BlazeposeDetector extends BasePoseDetector {
> ```

the BasePoseDetector class should have a dispose method, where it should release the models and other tensors held by the detector.
___
*[pose-detection/src/blazepose/detector.ts, line 106 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaLWOq0Jlgyt6181aD:-MWaLWOq0Jlgyt6181aE:b-gspsw2) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L106)):*
> ```XML
>    *
>    * @param config
>    *       maxPoses: Max number of poses to estimate. When maxPoses = 1, a
> ```

is the maxPoses optional too? Is it default to 1?
___
*[pose-detection/src/blazepose/detector.ts, line 119 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaLaqX2QsF-cPAAe7y:-MWaLaqX2QsF-cPAAe7z:b-5tzydn) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L119)):*
> ```XML
>   async estimatePoses(
>       image: PoseDetectorInput,
>       estimationConfig: BlazeposeEstimationConfig): Promise<Pose[]> {
> ```

should the config be an optional param?
___
*[pose-detection/src/blazepose/detector.ts, line 181 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaICsXEt9Q75Rlt41K:-MWaICsXEt9Q75Rlt41L:blp0q94) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L181)):*
> ```XML
> 
>   // Detects poses.
>   // Subgraph: PoseDetectionCpu.
> ```

what is the subgraph here referring to?
___
*[pose-detection/src/blazepose/index.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaIjTG7q5u9G9UhqLe:-MWaIjTG7q5u9G9UhqLf:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/index.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2019 Google LLC. All Rights Reserved.
> ```

2021
___
*[pose-detection/src/blazepose/calculators/remove_detection_letterbox.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaM6Cz8Gxy_gbAy96y:-MWaM6Cz8Gxy_gbAy96z:b-76mhd3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/calculators/remove_detection_letterbox.ts#L39)):*
> ```XML
>   const left = letterboxPadding.left;
>   const top = letterboxPadding.top;
>   const leftAndRight = letterboxPadding.left + letterboxPadding.right;
> ```

will leftAndRight and topAndBottom ever be 1 and causing dividedByZero error?


<!-- Sent from Reviewable.io -->

2021-03-25 00:23 UTC, lina128 reviewed
Thank you for the detailed review, Ping! Please take another look!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-:-MWakYQF7je6gkVJQTxP:bibzbcn)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)

___
*[pose-detection/demo/src/camera.js, line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaDXCLEbO1qZ-2YxHE:-MWafADeES7X0IE6ynhD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/camera.js#L99)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

shouldScale
</blockquote></details>

Done.
___
*[pose-detection/demo/src/index.js, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaEQaEEWRMYimtbv3v:-MWafEW294gcYOjFSPIl:b-p6rrjk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/index.js#L33)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this be just `model` instead of `STATE.model.model`? same for the mediapipe case
</blockquote></details>

I imagine model is an object, for each model, it should have a modelName and a couple of parameters. I can change it to STATE.model.name
___
*[pose-detection/demo/src/index.js, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaFtC27F2yO5fc7n5o:-MWah8ev8T8VLLg3Q1KU:bcuv5bp) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/index.js#L67)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the created model be cached? 
Also, if it is not cached,  there should be model dispose step?
</blockquote></details>

It is cached in the createDetector method. I moved it out and cache in the detector variable in this method to make it clearer. Also added dispose.
___
*[pose-detection/demo/src/index.js, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaErHr51tTwWLWJiKY:-MWahaYo31JDTC8oIm_5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/demo/src/index.js#L84)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
>  camera.drawResult(poses[0]);
> ```
will  ````
const shouldScale = STATE.model.model === posedetection.SupportedModels.MediapipeBlazepose;
camera.drawResult(poses[0],  shouldScale);
``` 
be cleaner? 

</blockquote></details>

Done.
___
*[pose-detection/src/create_detector.ts, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaGsvP51ZrQSqdh4pM:-MWahgUn5px2B7jJfEbu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/create_detector.ts#L38)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does this need to be casted to `BlazeposeModelConfig`?
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/blazepose_test.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaHFAhC-1dsDjwL9lF:-MWai57U0gqSG5KrOxCO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/blazepose_test.ts#L24)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you may want to add a test for checking memory leak after model is disposed.
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/detector.ts, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaL0ugBO8umj_ZTDB2:-MWai_uY8iluG-UtDFg7:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L53)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

the BasePoseDetector class should have a dispose method, where it should release the models and other tensors held by the detector.
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/detector.ts, line 106 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaLWOq0Jlgyt6181aD:-MWaijmM3C24Cgfy-kU_:b-zbla1r) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L106)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is the maxPoses optional too? Is it default to 1?
</blockquote></details>

It is required. My thinking is because we no longer have singlePose and multiPose api, Requiring user to explicitly set the maxPose makes it more readable whether singlePose or multiple poses will return. But I don't have strong opinion on this. I'm fine setting a default.
___
*[pose-detection/src/blazepose/detector.ts, line 181 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaICsXEt9Q75Rlt41K:-MWajsrB4UvK8ym1XQTq:b-etjzlj) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L181)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

what is the subgraph here referring to?
</blockquote></details>

It is referring to Xeno's subgraph, this will make it easier to track the source pipeline/code.
___
*[pose-detection/src/blazepose/index.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaIjTG7q5u9G9UhqLe:-MWak6lV5K9CjyKs-Ru3:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/index.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/remove_detection_letterbox.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaM6Cz8Gxy_gbAy96y:-MWakOtI3q2UEwtj29iC:b-a0nmbl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/calculators/remove_detection_letterbox.ts#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

will leftAndRight and topAndBottom ever be 1 and causing dividedByZero error?
</blockquote></details>

Theoretically it's possible, in reality, probably not. There's no value check in the source code.


<!-- Sent from Reviewable.io -->

2021-03-25 00:30 UTC, pyu10055 approved these changes
Great work, thanks you!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-:-MWamUi02Y9920mS-OHZ:b8cravw)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 106 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaLWOq0Jlgyt6181aD:-MWam4Sg2DXaTb8ftqs0:b5x39cl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L106)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

It is required. My thinking is because we no longer have singlePose and multiPose api, Requiring user to explicitly set the maxPose makes it more readable whether singlePose or multiple poses will return. But I don't have strong opinion on this. I'm fine setting a default.
</blockquote></details>

got it, I think it would be good to have a default value, since we are recommending single pose, and in JS there is no typing check.


<!-- Sent from Reviewable.io -->

2021-03-25 00:30 UTC, pyu10055 reviewed
> Reviewed 22 of 29 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)



<!-- Sent from Reviewable.io -->

2021-03-25 02:03 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 106 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaLWOq0Jlgyt6181aD:-MWb6mrV5zB2d_4HeSl7:b-sip4if) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L106)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

got it, I think it would be good to have a default value, since we are recommending single pose, and in JS there is no typing check.
</blockquote></details>

Got it. Changed maxPoses to optional and added default config.
___
*[pose-detection/src/blazepose/detector.ts, line 119 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWaLaqX2QsF-cPAAe7y:-MWb6r_w9OYbvE39WaE8:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L119)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the config be an optional param?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 02:19 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts
> +        (landmark.z - top) / (1 - leftAndRight);  // Scale Z coordinate as X.
Should be just `landmark.z` instead of `(landmark.z - top)`.

2021-03-25 02:19 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/calculators/transform_rect.ts
> +  } else {
SHouldn't it be `else if (config.squareShort)`?

2021-03-25 02:19 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector.ts
> +    this.maxPoses = config.maxPoses;
Is it even used? Looks like you are taking only the first one below anyway

2021-03-25 02:19 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector.ts
> +      image3d.dispose();
Why you dispose image only here and not in other returns?

2021-03-25 02:19 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector.ts
> +    // [1 (batch), 896 (anchor points), 13 (data for each anchor)]
Copy paste?

2021-03-25 02:19 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector.ts
> +
I'd move these numbers to constants

2021-03-25 17:20 UTC, lina128 reviewed
Hi Ivan, thank you for the detailed review! Please take another look, thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-:-MWeOk3G3D7uebXiehPX:b-afctgd)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 126 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBg-r1-126:-MWeEXuu30hnMt05kOBq:biom5ev) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L126)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Is it even used? Looks like you are taking only the first one below anyway
</blockquote></details>

It is used in detectPose, where maxPoses is passed to nonMaxSuppression. I guess it is for supporting multi-pose use case in the future? If maxPoses is larger than 1, then nonMaxSuppression will return maxPoses number of detection boxes at most. Then we just need to change the logic below that only takes the first one to take all of them and predict a set of landmarks for each and also the logic to update previous detection boxes. From the source code, it seems the nonMaxSuppression calculator just uses default max_num_detections, which is 2: 
https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection_cpu.pbtxt#L140-L142
https://github.com/google/mediapipe/blob/cccf6244d3fc4afc53082a397e764a8560eec96e/mediapipe/calculators/util/non_max_suppression_calculator.proto#L34

And then it only takes the first one in the pipeline: https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_cpu.pbtxt#L150
___
*[pose-detection/src/blazepose/detector.ts, line 158 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBg-r1-158:-MWeH8pMCr5hnYNvPENi:b1ymqaq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L158)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Why you dispose image only here and not in other returns?
</blockquote></details>

Ah, nice catch. Done.
___
*[pose-detection/src/blazepose/detector.ts, line 285 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBg-r1-285:-MWeHpc_BIqdFq4K6una:bss4a2b) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L285)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Copy paste?
</blockquote></details>

Removed.
___
*[pose-detection/src/blazepose/detector.ts, line 341 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBg-r1-341:-MWeIf1m9qIMKc8kMU_A:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/detector.ts#L341)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

I'd move these numbers to constants
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBS-r1-49:-MWeLmQ96LiJOs1sP9VF:bpfv421) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts#L49)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Why modifying input array and not creating new one?
</blockquote></details>

Created new output array. 
___
*[pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts, line 45 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBa-r1-45:-MWeM85f31HqFaaGBtZa:bhmhk5s) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts#L45)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Should be just `landmark.z` instead of `(landmark.z - top)`.
</blockquote></details>

Nice catch! Done.
___
*[pose-detection/src/blazepose/calculators/transform_rect.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBe-r1-61:-MWeMby52U5jy0gsZK0r:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/calculators/transform_rect.ts#L61)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

SHouldn't it be `else if (config.squareShort)`?
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/interfaces/config_interfaces.ts, line 17 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBW-r1-17:-MWeNry28Z3DQmZz49c1:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/c1f888a4691d966a9a93ff3e0dd1c0eddb281a4b/pose-detection/src/blazepose/calculators/interfaces/config_interfaces.ts#L17)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Comments to the fields?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 17:54 UTC, ivan-grishchenko approved these changes

2021-03-25 17:54 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts
>      const landmark = landmarks[i];
Does look like it creates copy of the landmark. You are still editing original one, no?

2021-03-25 17:54 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector_utils.ts
> +  let config = estimationConfig;
Same thing. I don't know how JS handles it, but doesn't look like copy of an object.

2021-03-25 18:24 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector_utils.ts, line 56 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBh-r4-56:-MWeb9V12xUBNvX5D11u:bjx8744) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f6f1964cfe297309f6248b0ebba28499c3243efb/pose-detection/src/blazepose/detector_utils.ts#L56)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Same thing. I don't know how JS handles it, but doesn't look like copy of an object.
</blockquote></details>

Nice catch! Changed to copy. `let config = estimationConfig;` will point to the same object. `let config = {...estimationConfig};` will spread the underlying attributes and use them to construct a new object, one caveat is it is a shallow copy, which mean if the underlying attributes are objects, only their pointer is copied. But given the config's attributes are all primitive types, we are fine.
___
*[pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts, line 38 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWSE9cZRSiMrjuXudBS-r4-38:-MWec6xXAOldTFw8YCSC:bb5zaf9) ([raw file](https://github.com/tensorflow/tfjs-models/blob/f6f1964cfe297309f6248b0ebba28499c3243efb/pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts#L38)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Does look like it creates copy of the landmark. You are still editing original one, no?
</blockquote></details>

Changed to copy.


<!-- Sent from Reviewable.io -->

2021-03-25 22:22 UTC, bazarevsky approved these changes

2021-03-25 23:02 UTC, mhays-google requested changes
> Reviewed 5 of 7 files at r3, 5 of 6 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 40 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfZo-jAde3N6cEggdr:-MWfZo-jAde3N6cEggds:bz2ioov) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector.ts#L40)):*
> ```XML
> import {tensorsToLandmarks} from './calculators/tensors_to_landmarks';
> import {transformNormalizedRect} from './calculators/transform_rect';
> import {BLAZEPOSE_DETECTOR_ANCHOR_CONFIGURATION, BLAZEPOSE_DETECTOR_IMAGE_TO_TENSOR_CONFIG, BLAZEPOSE_DETECTOR_NON_MAX_SUPPRESSION_CONFIGURATION, BLAZEPOSE_DETECTOR_RECT_TRANSFORMATION_CONFIG, BLAZEPOSE_LANDMARK_IMAGE_TO_TENSOR_CONFIG, BLAZEPOSE_NUM_AUXILIARY_KEYPOINTS_FULLBODY, BLAZEPOSE_NUM_AUXILIARY_KEYPOINTS_UPPERBODY, BLAZEPOSE_NUM_KEYPOINTS_FULLBODY, BLAZEPOSE_NUM_KEYPOINTS_UPPERBODY, BLAZEPOSE_POSE_PRESENCE_SCORE, BLAZEPOSE_TENSORS_TO_DETECTION_CONFIGURATION, BLAZEPOSE_TENSORS_TO_LANDMARKS_CONFIG_FULLBODY, BLAZEPOSE_TENSORS_TO_LANDMARKS_CONFIG_UPPERBODY, DEFAULT_BLAZEPOSE_ESTIMATION_CONFIG} from './constants';
> ```

I'm afraid to look... are there other constants that prevent you from wildcarding here?
___
*[pose-detection/src/blazepose/detector.ts, line 90 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWf_AWH0Nmg2hHNsaq2:-MWf_AWH0Nmg2hHNsaq3:b-2yhozo) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector.ts#L90)):*
> ```
>     const detectorModel = await tfconv.loadGraphModel(config.detectorModelUrl);
>     const landmarkModel = await tfconv.loadGraphModel(config.landmarkModelUrl);
> ```
This is fine, but if you want to kick off multiple download streams, consider:

```
await Promise.all([tfconv.loadGraphModel..., tfconv.loadGraphModel...]);
```
___
*[pose-detection/src/blazepose/detector.ts, line 310 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWf_q2OCob61Sk87Jho:-MWf_q2OCob61Sk87Jhp:b-4fi0m3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector.ts#L310)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     if (this.upperBodyOnly) {
>       landmarkTensor = landmarkResult[1] as tf.Tensor2D;
>       poseFlag = landmarkResult[2] as tf.Tensor2D;
>     } else {
>       landmarkTensor = landmarkResult[3] as tf.Tensor2D;
>       poseFlag = landmarkResult[2] as tf.Tensor2D;
>     }
> ```
</details>


could this be replaced with:

```
landmarkTensor = landmarkResult[this.upperBodyOnly ? 1 : 3] as tf.Tensor2D;
poseFlag = landmarkResult[2] as tf.Tensor2D;
```
___
*[pose-detection/src/blazepose/detector_utils.ts, line 26 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfaLwh-_i8QTg7KgpZ:-MWfaLwh-_i8QTg7Kgp_:by6y3eq) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector_utils.ts#L26)):*
> ```XML
> 
>   if (modelConfig == null) {
>     config = DEFAULT_BLAZEPOSE_FULLBODY_CONFIG;
> ```

You are going to mutate the object below, should you do `{...DEFAULT_BLAZEPOSE_FULLBODY_CONFIG}`?
___
*[pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts, line 37 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfadqx0oUf7vI3au8V:-MWfadqx0oUf7vI3au8W:bmz5wku) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts#L37)):*
> ```
>   for (let i = 0; i < landmarks.length; ++i) {
>     const landmark = landmarks[i];
> ```

You aren't using `i`. Maybe `for (const landmark of landmarks) {`
___
*[pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts, line 40 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfanBn4Iu_pc6Sb1-O:-MWfanBn4Iu_pc6Sb1-P:b-5w8d63) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts#L40)):*
> ```
>   for (let i = 0; i < rawLandmark.length; ++i) {
> ```

maybe `for (const landmark of rawLandmark)`


<!-- Sent from Reviewable.io -->

2021-03-25 23:15 UTC, lina128 reviewed
Thank you for the detailed review, Michael! Please take another look.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-:-MWfeq2n65-isJOff_6m:b-jxbzq5)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 40 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfZo-jAde3N6cEggdr:-MWfcyWe5viYh3sgAks6:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector.ts#L40)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

I'm afraid to look... are there other constants that prevent you from wildcarding here?
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/detector.ts, line 90 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWf_AWH0Nmg2hHNsaq2:-MWfdFLE4ApSk3pS7zHJ:bdcv6kv) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector.ts#L90)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

> ```
>     const detectorModel = await tfconv.loadGraphModel(config.detectorModelUrl);
>     const landmarkModel = await tfconv.loadGraphModel(config.landmarkModelUrl);
> ```
This is fine, but if you want to kick off multiple download streams, consider:

```
await Promise.all([tfconv.loadGraphModel..., tfconv.loadGraphModel...]);
```
</blockquote></details>

Good point!
___
*[pose-detection/src/blazepose/detector.ts, line 310 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWf_q2OCob61Sk87Jho:-MWfdbSmCkm-wQiPwKXP:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector.ts#L310)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

> ```
>     if (this.upperBodyOnly) {
>       landmarkTensor = landmarkResult[1] as tf.Tensor2D;
>       poseFlag = landmarkResult[2] as tf.Tensor2D;
>     } else {
>       landmarkTensor = landmarkResult[3] as tf.Tensor2D;
>       poseFlag = landmarkResult[2] as tf.Tensor2D;
>     }
> ```

could this be replaced with:

```
landmarkTensor = landmarkResult[this.upperBodyOnly ? 1 : 3] as tf.Tensor2D;
poseFlag = landmarkResult[2] as tf.Tensor2D;
```
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/detector_utils.ts, line 26 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfaLwh-_i8QTg7KgpZ:-MWfdkca79xJqIByS4U0:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/detector_utils.ts#L26)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

You are going to mutate the object below, should you do `{...DEFAULT_BLAZEPOSE_FULLBODY_CONFIG}`?
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts, line 37 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfadqx0oUf7vI3au8V:-MWfdw-g7FBmSgEaeGEm:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/calculators/calculate_landmark_projection.ts#L37)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

> ```
>   for (let i = 0; i < landmarks.length; ++i) {
>     const landmark = landmarks[i];
> ```

You aren't using `i`. Maybe `for (const landmark of landmarks) {`
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts, line 40 at r5](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWfanBn4Iu_pc6Sb1-O:-MWfeSYDB65TY8hllMwp:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/3fd318043692310497aab6677e159dd1e657f5b1/pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts#L40)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

> ```
>   for (let i = 0; i < rawLandmark.length; ++i) {
> ```

maybe `for (const landmark of rawLandmark)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 23:21 UTC, mhays-google requested changes
> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts, line 42 at r6](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWffjZL28tEeasKcUsl:-MWffjZL28tEeasKcUsm:bhraku3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/78b0de6b84eaa0b9438566cfae1a1ea7d991dd12/pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts#L42)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     const outLandmark = {...landmark};
>     const newX = (landmark.x - left) / (1 - leftAndRight);
>     const newY = (landmark.y - top) / (1 - topAndBottom);
>     const newZ = landmark.z / (1 - leftAndRight);  // Scale Z coordinate as X.
>     outLandmark.x = newX;
>     outLandmark.y = newY;
>     outLandmark.z = newZ;
>     outLandmarks.push(outLandmark);
> ```
</details>


even better:

```
const outLandmark = {
  ...landmark,
  x: (landmark.x - left) / (1 - leftAndRight);
  y: (landmark.y - top) / (1 - topAndBottom);
}
```

even even cooler:

```
const outLandmarks = rawLandmark.map( landmark => {
  ...landmark,
  x: (landmark.x - left) / (1 - leftAndRight);
  y: (landmark.y - top) / (1 - topAndBottom);
});
```


<!-- Sent from Reviewable.io -->

2021-03-25 23:22 UTC, mhays-google approved these changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts, line 42 at r6](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWffjZL28tEeasKcUsl:-MWfgQxu3qv2pVlhVhr9:bo841ez) ([raw file](https://github.com/tensorflow/tfjs-models/blob/78b0de6b84eaa0b9438566cfae1a1ea7d991dd12/pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts#L42)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

> ```
>     const outLandmark = {...landmark};
>     const newX = (landmark.x - left) / (1 - leftAndRight);
>     const newY = (landmark.y - top) / (1 - topAndBottom);
>     const newZ = landmark.z / (1 - leftAndRight);  // Scale Z coordinate as X.
>     outLandmark.x = newX;
>     outLandmark.y = newY;
>     outLandmark.z = newZ;
>     outLandmarks.push(outLandmark);
> ```

even better:

```
const outLandmark = {
  ...landmark,
  x: (landmark.x - left) / (1 - leftAndRight);
  y: (landmark.y - top) / (1 - topAndBottom);
}
```

even even cooler:

```
const outLandmarks = rawLandmark.map( landmark => {
  ...landmark,
  x: (landmark.x - left) / (1 - leftAndRight);
  y: (landmark.y - top) / (1 - topAndBottom);
});
```
</blockquote></details>

You can actually replace this entire creation section with those lines above.


<!-- Sent from Reviewable.io -->

2021-03-25 23:29 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/616)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts, line 42 at r6](https://reviewable.io/reviews/tensorflow/tfjs-models/616#-MWffjZL28tEeasKcUsl:-MWfi08R0GCK3vqFklF_:b-r2pbca) ([raw file](https://github.com/tensorflow/tfjs-models/blob/78b0de6b84eaa0b9438566cfae1a1ea7d991dd12/pose-detection/src/blazepose/calculators/remove_landmark_letterbox.ts#L42)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

You can actually replace this entire creation section with those lines above.
</blockquote></details>

Nice, done. Thank you for the suggestion!


<!-- Sent from Reviewable.io -->

2021-03-25 23:44 UTC, merged