[pose-detection]Refactor pipeline.
tensorflow/tfjs-models pull request #622
Opened 2021-03-29 20:56 UTC by lina128

Remove early returns in the pipeline, let result propagate through pipeline in order for downstream filters to have a chance to reset states if detections is empty or landmarks is empty.

2021-03-29 21:02 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @mhays-google)

___
*[pose-detection/src/blazepose/blazepose_test.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzm5xC5fu7WYA4WDy9:-MWzm5xC5fu7WYA4WDyA:bxq1caz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d884bb6c5d670341ba26f6777889eca9678bf4c0/pose-detection/src/blazepose/blazepose_test.ts#L32)):*
> ```XML
>   beforeAll(() => {
>     timeout = jasmine.DEFAULT_TIMEOUT_INTERVAL;
>     jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000000;
> ```

what is the reason for setting such a large timeout limit?


<!-- Sent from Reviewable.io -->

2021-03-29 21:05 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622)* status: 0 of 1 approvals obtained (waiting on @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/blazepose_test.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzm5xC5fu7WYA4WDy9:-MWzn43yEVJdy6ptClbA:boclp5m) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d884bb6c5d670341ba26f6777889eca9678bf4c0/pose-detection/src/blazepose/blazepose_test.ts#L32)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

what is the reason for setting such a large timeout limit?
</blockquote></details>

Without increase the timeout, it failed before model loading is complete. Just set a large one to allow model loading, it is set back to previous timeout after this test. This is the same trick we use for tfjs repo. The model loading may not need the whole time, but setting a large number basically eliminate flakiness.


<!-- Sent from Reviewable.io -->

2021-03-29 21:09 UTC, pyu10055 approved these changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko and @mhays-google)



<!-- Sent from Reviewable.io -->

2021-03-29 21:36 UTC, ivan-grishchenko requested changes

2021-03-29 21:36 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector.ts
> +      return {actualLandmarks: [], auxiliaryLandmarks: [], poseScore};
Looks like propagating `null` instead of `[]` is better in general case cause empty array is can be a valid output in some other cases.

2021-03-29 21:36 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector.ts
> +    if (landmarks.length === 0) {
And then it will be checking for `null` here.

2021-03-29 21:36 UTC, ivan-grishchenko commented on pose-detection/src/blazepose/detector.ts
> +      this.regionOfInterest = null;
It looks strange that `regionOfInterest` is a state of the detector. Shouldn't it be just parameter or the call?

2021-03-29 22:00 UTC, lina128 reviewed
Hi Ivan, thank you for the comments. I changed to landmarks to null instead of empty array. Also added null check to visibility filter, please take another look. Thank you!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-:-MWzzwL95SIHEN8o75aj:b-h4ryml)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko and @mhays-google)

___
*[pose-detection/src/blazepose/detector.ts, line 139 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzlRWEQPcut6PpVDNL-r1-139:-MWzuysu9EPNECvpyJWU:bpmd620) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d884bb6c5d670341ba26f6777889eca9678bf4c0/pose-detection/src/blazepose/detector.ts#L139)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

It looks strange that `regionOfInterest` is a state of the detector. Shouldn't it be just parameter or the call?
</blockquote></details>

regionOfInterest is cached as a state of the detector, so that for next frame, if regionOfInterest exists, it doesn't have to run the detection model again.
___
*[pose-detection/src/blazepose/detector.ts, line 325 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzlRWEQPcut6PpVDNL-r1-325:-MWzvW_TB5GJWXVFTjNd:b-qif770) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d884bb6c5d670341ba26f6777889eca9678bf4c0/pose-detection/src/blazepose/detector.ts#L325)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Looks like propagating `null` instead of `[]` is better in general case cause empty array is can be a valid output in some other cases.
</blockquote></details>

I agree, the meaning of null and [] is different, changed to null.
___
*[pose-detection/src/blazepose/detector.ts, line 375 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzlRWEQPcut6PpVDNL-r1-375:-MWzxIYa495sJ1ToVVPW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d884bb6c5d670341ba26f6777889eca9678bf4c0/pose-detection/src/blazepose/detector.ts#L375)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

And then it will be checking for `null` here.
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/visibility_smoothing.ts, line 34 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzzt_63Nf04PW6ceNs:-MWzzt_63Nf04PW6ceNt:b-wj6zak) ([raw file](https://github.com/tensorflow/tfjs-models/blob/43444b4e38575e7d9fb0f10e9a74cdfaee3f77fb/pose-detection/src/blazepose/calculators/visibility_smoothing.ts#L34)):*
> ```XML
> 
>   apply(landmarks: Keypoint[]): Keypoint[] {
>     if (landmarks == null) {
> ```

Added null check. @ivan-grishchenko 


<!-- Sent from Reviewable.io -->

2021-03-29 22:19 UTC, ivan-grishchenko approved these changes

2021-03-29 22:59 UTC, mhays-google requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko and @lina128)

___
*[pose-detection/demo/src/camera.js, line 93 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MX-BnIQ-IcW73vbxiOV:-MX-BnIQ-IcW73vbxiOW:bd6qds4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/43444b4e38575e7d9fb0f10e9a74cdfaee3f77fb/pose-detection/demo/src/camera.js#L93)):*
> ```
> .keypoints
> ```
Not for this cl -- is there a way to add closure syntax?  That would have caught this issue.
___
*[pose-detection/src/blazepose/detector.ts, line 375 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzlRWEQPcut6PpVDNL-r1-375:-MX-CExPA4_qds95XGSZ:bavey5p) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d884bb6c5d670341ba26f6777889eca9678bf4c0/pose-detection/src/blazepose/detector.ts#L375)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If this is a real check, then you should really change the method signature to make landmarks optional. 
___
*[pose-detection/src/blazepose/calculators/visibility_smoothing.ts, line 34 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzzt_63Nf04PW6ceNs:-MX-CeyX9sj2FCR6od0e:bd47416) ([raw file](https://github.com/tensorflow/tfjs-models/blob/43444b4e38575e7d9fb0f10e9a74cdfaee3f77fb/pose-detection/src/blazepose/calculators/visibility_smoothing.ts#L34)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Added null check. @ivan-grishchenko 
</blockquote></details>

same as above...


<!-- Sent from Reviewable.io -->

2021-03-30 05:05 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko and @lina128)

___
*[pose-detection/src/blazepose/detector.ts, line 375 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzlRWEQPcut6PpVDNL-r1-375:-MX0VINODzb2D7x0Tfgq:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d884bb6c5d670341ba26f6777889eca9678bf4c0/pose-detection/src/blazepose/detector.ts#L375)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

If this is a real check, then you should really change the method signature to make landmarks optional. 
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/visibility_smoothing.ts, line 34 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzzt_63Nf04PW6ceNs:-MX0W2-52j0lNko7_qha:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/43444b4e38575e7d9fb0f10e9a74cdfaee3f77fb/pose-detection/src/blazepose/calculators/visibility_smoothing.ts#L34)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

same as above...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-30 17:24 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ivan-grishchenko, @lina128, and @mhays-google)

___
*[pose-detection/src/blazepose/blazepose_test.ts, line 31 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/622#-MWzlRWEQPcut6PpVDNK-r3-31:-MX38Ugf2G6lPZM31mG7:bxojne5) ([raw file](https://github.com/tensorflow/tfjs-models/blob/8bde08d2cdc5e9d92f2586e5bb38032497ee8daa/pose-detection/src/blazepose/blazepose_test.ts#L31)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

1000000 is super dangerous.   That's 16 minutes for each test that hangs.  I would take the length the test actually runs and then increase it by some percentage. 

How to deal with actual flakiness?  First, run your `blaze test` with something like: --runs_per_test=10 to get an idea of how flaky it really is.  I would personally include the timeout until it's no longer flaky, but in the meantime, you can tag your build rule with `flaky=1`.  See: go/flaky
</blockquote></details>

That's a great suggestion, unfortunately we don't have blaze outside of Google. We pretty much setup the CI infra ourselves. We wrote a flaky run script ourselves, I will integrate that to this repo later:https://github.com/tensorflow/tfjs/blob/ec1e966e25e89daf451b2d3bcd1775371c0ba7e7/scripts/run_flaky.js
Change it to 2mins for now.


<!-- Sent from Reviewable.io -->

2021-03-30 17:29 UTC, mhays-google approved these changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/622)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ivan-grishchenko and @lina128)



<!-- Sent from Reviewable.io -->

2021-03-30 17:29 UTC, merged