[pose-detection]Add landmark filter.
tensorflow/tfjs-models pull request #625
Opened 2021-03-31 01:57 UTC by lina128

This PR has below changes:
1. Add relative velocity filter.
2. Add one euro filter.
3. Add landmark filter that uses velocity filter.

2021-03-31 16:03 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: 0 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @lina128, and @mhays-google)

___
*[pose-detection/src/blazepose/calculators/landmarks_smoothing.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX8-j6ODscVg-PxYJzY:-MX8-j6P-LNpP6Lc1RS2:bwnjjft) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_smoothing.ts#L47)):*
> ```XML
>     }
>     const imageSize = getImageSize(image);
>     const macroSeconds = image.currentTime * 1e6;
> ```

The DetectorInput type allows other types than HTMLVideoElement, for other types, will this cause problem?
___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX802jDAyA4gD-hZhob:b-gqd39v) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
> ```XML
>     // Filter landmarks. Every axis of every landmark is filtered separately.
>     return landmarks.map((landmark, i) => {
>       const outLandmark = {
> ```

Will the deconstruction and assignment of x and y fields in the same line guarantee the consistent order? Maybe consider using Object.assign
```
const outLandmark = Object.assign({}, landmark, 
    {x: this.xFilters[i].apply(landmark.x, macroSeconds),
     y: this.yFilters[i].apply(landmark.y, macroSeconds)
     })
```
___
*[pose-detection/src/calculators/one_euro_filter.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX809ZXD88I93SDFQb6:-MX809ZXD88I93SDFQb7:b-bqqomk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/calculators/one_euro_filter.ts#L66)):*
> ```XML
>     // Update the sampling frequency based on timestamps.
>     if (this.lastTimestamp !== 0 && $macroSeconds !== 0) {
>       const macroSecondsToSecond = 1e-6;
> ```

this value is used in many places, create a constant for it.
___
*[pose-detection/src/calculators/relative_velocity_filter.ts, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX80Ph15FGLUP1YOjX9:-MX80Ph15FGLUP1YOjXA:b-5tk1m6) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/calculators/relative_velocity_filter.ts#L84)):*
> ```XML
>       // frame rate, so assuming 30 values per second or 1 / 30 of a second is
>       // a good duration per window element.
>       const assumedMaxDuration = 1e6 / 30;
> ```

create constant for 1e6 


<!-- Sent from Reviewable.io -->

2021-03-31 17:02 UTC, lina128 reviewed
Thank you for the review Ping, please take another look!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-:-MX8DzxL8sKkzFW8vJOE:bwwlel2)* status: 0 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/landmarks_smoothing.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX8-j6ODscVg-PxYJzY:-MX8C3CV1Y5Y2kWvtRWW:b8zv1jg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_smoothing.ts#L47)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

The DetectorInput type allows other types than HTMLVideoElement, for other types, will this cause problem?
</blockquote></details>

image is only HTMLVideoElement type in this method.
___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX8CEkI71Lj9JvZkUVM:bqeuaom) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Will the deconstruction and assignment of x and y fields in the same line guarantee the consistent order? Maybe consider using Object.assign
```
const outLandmark = Object.assign({}, landmark, 
    {x: this.xFilters[i].apply(landmark.x, macroSeconds),
     y: this.yFilters[i].apply(landmark.y, macroSeconds)
     })
```
</blockquote></details>

Thanks for the tip! Why do we need to keep consistent order?
___
*[pose-detection/src/calculators/one_euro_filter.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX809ZXD88I93SDFQb6:-MX8Cww8DHMkwmYiuUjt:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/calculators/one_euro_filter.ts#L66)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this value is used in many places, create a constant for it.
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/relative_velocity_filter.ts, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX80Ph15FGLUP1YOjX9:-MX8Dy_y2kuBhOWMt9bs:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/calculators/relative_velocity_filter.ts#L84)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

create constant for 1e6 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-31 17:26 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: 0 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 446 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX8JW-JCG68cyAaRWiJ:-MX8JW-JCG68cyAaRWiK:b-8m1zgs) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/detector.ts#L446)):*
> ```XML
>       }
>       actualLandmarksFiltered = this.landmarksSmoothingFilterActual.apply(
>           actualLandmarksFiltered, image);
> ```

there is no type check for HTMLVideoElement, will this causing issue in the filter code?
___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX8JIhh-2FSyD6Bx5uX:b9i1igy) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Thanks for the tip! Why do we need to keep consistent order?
</blockquote></details>

you are overwriting the x and y fields of landmark, right?


<!-- Sent from Reviewable.io -->

2021-03-31 17:53 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: 0 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 446 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX8JW-JCG68cyAaRWiJ:-MX8PTs5-yOtHq3mhS1f:bx6wxre) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/detector.ts#L446)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

there is no type check for HTMLVideoElement, will this causing issue in the filter code?
</blockquote></details>

There is type check, the isVideo function is a typescript type guard.
___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX8PaWi-xYV3WZt0Cz0:bacakaa) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you are overwriting the x and y fields of landmark, right?
</blockquote></details>

Landmark will not be changed, outLandmark copies the value from landmark and set new value for x and y, right?


<!-- Sent from Reviewable.io -->

2021-03-31 19:09 UTC, ivan-grishchenko commented on pose-detection/src/calculators/one_euro_filter.ts
> +          1 / (($macroSeconds - this.lastTimestamp) * MACRO_SECONDS_TO_SECOND);
Original implementation uses NANOseconds (1e-9 instead of 1e-6). Again, not sure how it will change the result.

2021-03-31 19:15 UTC, ivan-grishchenko commented on pose-detection/src/calculators/relative_velocity_filter.ts
> +          value * valueScale - this.lastValue * this.lastValueScale;
FYI, I see you used the legacy distance estimation mode. And that's what we use in our code. But probably we'll update

2021-03-31 19:17 UTC, mhays-google requested changes
> Reviewed 12 of 17 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: 0 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @lina128, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX8fZoa6q6hrtRO7M2g:b-miebl3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Landmark will not be changed, outLandmark copies the value from landmark and set new value for x and y, right?
</blockquote></details>

During transpile to ES5, ...landmark is most likely converted to for..of syntax.
___
*[pose-detection/src/calculators/one_euro_filter.ts, line 87 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX8hDg68tn1ZhRX43Zp:-MX8hDg7DDbCxunoEH-W:b-f4xhiw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/calculators/one_euro_filter.ts#L87)):*
> ```
>     const te = 1.0 / this.frequency;
>     const tau = 1.0 / (2 * Math.PI * cutoff);
>     return 1.0 / (1.0 + tau / te);
> ```
nit... a bit of extra divisions going on.. I dunno if the compiler is smart enough to break it down, but maaaaaybe simplify the equation?


<!-- Sent from Reviewable.io -->

2021-03-31 19:18 UTC, ivan-grishchenko commented on pose-detection/src/calculators/relative_velocity_filter.ts
> +      this.window.push({distance, duration});
For the loop above it's important where new elements are pushed into the window. You reversed the order in the window, but kept the loop not reversed.

2021-03-31 19:41 UTC, lina128 reviewed
Hi @ivan-grishchenko  and @mhays-google , thank you for the great feedback, please take another look!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-:-MX8nAgp05nB4KwvLE7-:b-xxox4m)* status: 0 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/landmarks_smoothing.ts, line 37 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX4zuOA_6CwZ18m6DkO-r2-37:-MX8jxI-19aW7EnHA5Hc:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/blazepose/calculators/landmarks_smoothing.ts#L37)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

I would check for `config.oneEuroFilter != null` and add `else` section that throws error so that when in future new filter is added you won't forget to update it here.
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/landmarks_smoothing.ts, line 48 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX4zuOA_6CwZ18m6DkO-r2-48:-MX8kMBz2Cg0L19w4ow0:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/blazepose/calculators/landmarks_smoothing.ts#L48)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Same with SECOND_TO_MACRO_SECONDS
</blockquote></details>

Done.
___
*[pose-detection/src/blazepose/calculators/interfaces/common_interfaces.ts, line 21 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX5R9V7wReRGOk5agrE-r2-21:-MX8l7bAAJXvewNO0nFY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/blazepose/calculators/interfaces/common_interfaces.ts#L21)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

What are MACROseconds? I only know MICROseconds
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/one_euro_filter.ts, line 68 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX4zuOA_6CwZ18m6DkY-r2-68:-MX8lBxnEIxv6Sryrpwg:b-20z5hf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/calculators/one_euro_filter.ts#L68)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

Original implementation uses NANOseconds (1e-9 instead of 1e-6). Again, not sure how it will change the result.
</blockquote></details>

Right, original implementation uses int64, but browser doesn't have int64, so I'm concerned that use nanoseconds is more likely to overflow, right?
___
*[pose-detection/src/calculators/one_euro_filter.ts, line 87 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX8hDg68tn1ZhRX43Zp:-MX8lr7d8Vdf83by7TbX:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/calculators/one_euro_filter.ts#L87)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

> ```
>     const te = 1.0 / this.frequency;
>     const tau = 1.0 / (2 * Math.PI * cutoff);
>     return 1.0 / (1.0 + tau / te);
> ```
nit... a bit of extra divisions going on.. I dunno if the compiler is smart enough to break it down, but maaaaaybe simplify the equation?
</blockquote></details>

Done.
___
*[pose-detection/src/calculators/relative_velocity_filter.ts, line 76 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX4zuOA_6CwZ18m6DkZ-r2-76:-MX8ludjEUENU1CntQp2:b1w5yz5) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/calculators/relative_velocity_filter.ts#L76)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

FYI, I see you used the legacy distance estimation mode. And that's what we use in our code. But probably we'll update
</blockquote></details>

Got it, add TODO.
___
*[pose-detection/src/calculators/relative_velocity_filter.ts, line 101 at r2](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX4zuOA_6CwZ18m6DkZ-r2-101:-MX8n-OI0P1LesX6I7l-:b-h9u9my) ([raw file](https://github.com/tensorflow/tfjs-models/blob/ea92ebe37d36c2e9f47fd7d2bee1ae0656530f1b/pose-detection/src/calculators/relative_velocity_filter.ts#L101)):*
<details><summary><i>Previously, ivan-grishchenko wrote…</i></summary><blockquote>

For the loop above it's important where new elements are pushed into the window. You reversed the order in the window, but kept the loop not reversed.
</blockquote></details>

Ah, make sense. I've changed to adding new element to the front and pop from the back.


<!-- Sent from Reviewable.io -->

2021-03-31 20:46 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: 0 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @mhays-google, and @pyu10055)

___
*[pose-detection/src/calculators/one_euro_filter.ts, line 86 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX91IDJBMfjvDFTR1Y9:-MX91IDJBMfjvDFTR1YA:b-necn6f) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b30272baa8e036931459d17816c8313f80d69417/pose-detection/src/calculators/one_euro_filter.ts#L86)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     // te = 1.0 / this.frequency
>     // tau = 1.0 / (2 * Math.PI * cutoff)
>     // result = 1 / (1.0 + (tau / te))
>     return 1.0 / (1.0 + (this.frequency / (2 * Math.PI * cutoff)));
> ```
</details>

@mhays-google Please take another look, thank you!


<!-- Sent from Reviewable.io -->

2021-03-31 21:00 UTC, mhays-google reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX94DyE2voKcoC8VXCM:b-un4ubb) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

During transpile to ES5, ...landmark is most likely converted to for..of syntax.
</blockquote></details>

Just to double check... I ran the following through the transpiler at typescriptlang.org:

```
const a = {foo:bar};
const b = {...a, foo:'box'};
const c = {...b, ...a};
```

and it transformed into:

```
"use strict";
const a = { foo: bar };
const b = Object.assign(Object.assign({}, a), { foo: 'box' });
const c = Object.assign(Object.assign({}, b), a);
```

So it seems equivalent to using assign.


<!-- Sent from Reviewable.io -->

2021-03-31 21:02 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, and @pyu10055)

___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX94zFA4F5fVipxSyaW:b7e0d8x) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
<details><summary><i>Previously, mhays-google (Michael Hays) wrote…</i></summary><blockquote>

Just to double check... I ran the following through the transpiler at typescriptlang.org:

```
const a = {foo:bar};
const b = {...a, foo:'box'};
const c = {...b, ...a};
```

and it transformed into:

```
"use strict";
const a = { foo: bar };
const b = Object.assign(Object.assign({}, a), { foo: 'box' });
const c = Object.assign(Object.assign({}, b), a);
```

So it seems equivalent to using assign.
</blockquote></details>

Thank you so much for checking, Michael! It's great to confirm this.


<!-- Sent from Reviewable.io -->

2021-03-31 21:51 UTC, ivan-grishchenko approved these changes

2021-03-31 21:59 UTC, bazarevsky approved these changes

2021-03-31 21:59 UTC, bazarevsky commented on pose-detection/src/calculators/velocity_filter_utils.ts
> +  const x = landmarks.map(landmark => landmark.x);
In general, I expect that just square around for keypoints is not the best way to estimate object scale. And this approach can lead to fluctuations depending on scale. Torso as source of scale or distance between hidden center and rotation keypoints would be more stable way to estimate human pose scale.

2021-04-01 00:02 UTC, lina128 reviewed
Thank you @bazarevsky for the thoughtful review!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-:-MX9jF_T4xjdjHHnefgb:b-kdqph1)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, and @pyu10055)

___
*[pose-detection/src/calculators/velocity_filter_utils.ts, line 26 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX4zuOA_6CwZ18m6Dk_-r3-26:-MX9j0FL5qBQvgQ6ejnu:b-udhuuf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/b30272baa8e036931459d17816c8313f80d69417/pose-detection/src/calculators/velocity_filter_utils.ts#L26)):*
<details><summary><i>Previously, bazarevsky (v.bazarevsky) wrote…</i></summary><blockquote>

In general, I expect that just square around for keypoints is not the best way to estimate object scale. And this approach can lead to fluctuations depending on scale. Torso as source of scale or distance between hidden center and rotation keypoints would be more stable way to estimate human pose scale.
</blockquote></details>

That makes a lot of sense! Added a TODO, will follow up with you for a better approach. The distance between hidden center and rotation keypoints sounds good!


<!-- Sent from Reviewable.io -->

2021-04-01 00:38 UTC, pyu10055 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)

___
*[pose-detection/src/blazepose/detector.ts, line 446 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX8JW-JCG68cyAaRWiJ:-MX8fwzs9kpwYaoB-94o:b-e0jwdk) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/detector.ts#L446)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

There is type check, the isVideo function is a typescript type guard.
</blockquote></details>

I see, the isVideo()
___
*[pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/625#-MX802jDAyA4gD-hZhoa:-MX9rT562cDu7zu4mTuW:bj2ybgm) ([raw file](https://github.com/tensorflow/tfjs-models/blob/6f9cb5f05cfb487cdf0cca7b0a37fe7ceae77ad0/pose-detection/src/blazepose/calculators/landmarks_velocity_filter.ts#L61)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Thank you so much for checking, Michael! It's great to confirm this.
</blockquote></details>

awesome, thanks!


<!-- Sent from Reviewable.io -->

2021-04-01 00:39 UTC, pyu10055 approved these changes
> Reviewed 10 of 17 files at r1, 7 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/625)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @bazarevsky, @ivan-grishchenko, @lina128, @mhays-google, and @pyu10055)



<!-- Sent from Reviewable.io -->

2021-04-01 00:54 UTC, merged