[pose-detection] Add support for multi-pose MoveNet models (from URL only for now)
tensorflow/tfjs-models pull request #770
Opened 2021-08-02 22:48 UTC by ardoerlemans

2021-08-03 00:22 UTC, lina128 reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans)

___
*[pose-detection/src/movenet/detector.ts, line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8DlF2-gxywxJslT7_:-Mg8DlF2-gxywxJslT7a:btgq0i0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L96)):*
> ```
> const numKeypoints = 17;
> ```
Can you define this const in the constants.ts file?
___
*[pose-detection/src/movenet/detector.ts, line 140 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8EekOC1PWglo13ssE:-Mg8EekOC1PWglo13ssF:b-49o4sl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L140)):*
> ```
>     if (!this.moveNetModel) {
>       return null;
>     }
> ```
Can this condition happen?
___
*[pose-detection/src/movenet/detector.ts, line 145 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8Gva7AQV1oTxwbUYj:-Mg8Gva7AQV1oTxwbUYk:b-ehmy8f) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L145)):*
> ```
> !outputTensor
> ```
When will this happen?
___
*[pose-detection/src/movenet/detector.ts, line 151 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8EsGW6nOocqBZ_ekf:-Mg8EsGW6nOocqBZ_ekg:b6us9h5) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L151)):*
> ```
>     const numKeypoints = 17;
>     const boundingBoxSize = 5;  // ymin, xmin, ymax, xmax, score
> ```
Move this two constants to constants.ts
___
*[pose-detection/src/movenet/detector.ts, line 154 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8FEIACZy5L8g9OCsC:-Mg8FEIACZy5L8g9OCsD:b2khz90) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L154)):*
> ```
>     if (outputTensor.shape.length !== 3 || outputTensor.shape[0] !== 1 ||
>         outputTensor.shape[2] !== multiPoseInstanceSize) {
> ```
When will this condition happen?
___
*[pose-detection/src/movenet/detector.ts, line 178 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8GKziBXzdRSH98qyW:-Mg8GKziBXzdRSH98qyX:brjr1fy) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L178)):*
> ```
> 3
> ```
Change this to a constant.
___
*[pose-detection/src/movenet/detector.ts, line 245 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8Gg-m8fJfq5Cv4Ldf:-Mg8Gg-m8fJfq5Cv4Ldg:b-wd3ydt) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L245)):*
> ```
> !keypoints
> ```
It seems for singlePose, keypoints will never be falsy. Should you checkout the output of singlePose and set it to `null` instead of `[null]`?
___
*[pose-detection/src/movenet/detector.ts, line 252 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8Hx3C7oc7ThbgcXdB:-Mg8Hx3C7oc7ThbgcXdC:b-2metrw) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L252)):*
> ```
> i
> ```
sugg: poseIdx
___
*[pose-detection/src/movenet/detector.ts, line 255 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8HzTx4o10EGGLb9kS:-Mg8HzTx4o10EGGLb9kT:bmbnft1) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L255)):*
> ```
> j
> ```
sugg: keypointIdx
___
*[pose-detection/src/movenet/detector.ts, line 380 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8K6zM4U1WMAPG5NYQ:-Mg8K6zM4U1WMAPG5NYR:b-7a3fsn) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L380)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>       resizedImage =
>           tf.image.resizeBilinear(imageTensor4D, [resizedHeight, resizedWidth]);
>       paddedWidth = resizedWidth;
>       paddedHeight =
>           Math.ceil(resizedHeight / dimensionDivisor) * dimensionDivisor;
>       paddedImage = tf.pad(
>           resizedImage,
>           [[0, 0], [0, paddedHeight - resizedHeight], [0, 0], [0, 0]]);
> ```
</details>

This uses two ops to achieve the effect of making a squarish image with padding, consider use the convertImageToTensor calculator from `convert_image_to_tensor.ts`, which uses a single op to achieve the effect. It uses tf.transform to perform an affine transformation, should help squeeze some performance. Also from readability point of view, it reduces the whole if...else... block (approx. 16 lines of code) to 1 line.

PoseNet example: https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/src/posenet/detector.ts#L104
BlazePose example: https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/src/blazepose_tfjs/detector.ts#L223

We reduced the time spent to crop, resize and pad image from 17.68ms to 2.36ms.
___
*[pose-detection/src/movenet/detector.ts, line 414 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8MTkSACp4c_gLsvwA:-Mg8MTkSACp4c_gLsvwB:b8jy9f0) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L414)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     for (let i = 0; i < keypoints.length; ++i) {
>       for (let j = 0; j < keypoints[i].length; ++j) {
>         keypoints[i][j].y = keypoints[i][j].y * paddedHeight / resizedHeight;
>         keypoints[i][j].x = keypoints[i][j].x * paddedWidth / resizedWidth;
>       }
>     }
> ```
</details>

If you use above suggested calculator to pad and resize image, you can use the removeLetterbox calculator to remove padding and get the keypoints in the original image's coordinates: https://github.com/tensorflow/tfjs-models/blob/master/pose-detection/src/blazepose_tfjs/calculators/remove_landmark_letterbox.ts#L33

This calculator is currently not in the shared calculators folder, but in blazepose folder, I can move it to shared folder.
___
*[pose-detection/src/movenet/detector.ts, line 431 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8MuZD8fi1wZWc43oQ:-Mg8MuZD8fi1wZWc43oR:b-fe7b3i) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L431)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
>   filterCropRegion(newCropRegion: BoundingBox): BoundingBox {
>     if (!newCropRegion) {
>       this.cropRegionFilterYMin.reset();
>       this.cropRegionFilterXMin.reset();
>       this.cropRegionFilterYMax.reset();
>       this.cropRegionFilterXMax.reset();
>       return null;
>     } else {
>       const filteredYMin = this.cropRegionFilterYMin.apply(newCropRegion.yMin);
>       const filteredXMin = this.cropRegionFilterXMin.apply(newCropRegion.xMin);
>       const filteredYMax = this.cropRegionFilterYMax.apply(newCropRegion.yMax);
>       const filteredXMax = this.cropRegionFilterXMax.apply(newCropRegion.xMax);
>       return {
>         yMin: filteredYMin,
>         xMin: filteredXMin,
>         yMax: filteredYMax,
>         xMax: filteredXMax,
>         height: filteredYMax - filteredYMin,
>         width: filteredXMax - filteredXMin
>       };
>     }
>   }
> ```
</details>

nit: Consider move some of these stateless utils to a separate file to make detector.ts more readable, it's becoming longer and longer.
___
*[pose-detection/src/movenet/detector.t [...]

2021-08-03 14:28 UTC, ronnyvotel reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770)* status: 0 of 1 approvals obtained (waiting on @ardoerlemans)

___
*[pose-detection/src/movenet/detector.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKVAQ90IJpMDuMVDw:-MgBKVAQ90IJpMDuMVDx:b-c5k1hm) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L185)):*
> ```XML
>     }
> 
>     return keypoints;
> ```

Since we have them, shouldn't we store the boxes and box scores as well?
___
*[pose-detection/src/movenet/detector.ts, line 192 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKf6R9HsKBhi69ufk:-MgBKf6R9HsKBhi69ufl:bqfkhtg) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L192)):*
> ```
> should
> ```
remove
___
*[pose-detection/src/movenet/detector.ts, line 286 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBMFoc-Sv-NtBGIHFE:-MgBMFoc-Sv-NtBGIHFF:b5ht2sf) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L286)):*
> ```
> *
> ```
Maybe don't add spaces between @params, to be consistent
___
*[pose-detection/src/movenet/detector.ts, line 355 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBMwGGBfjIYYRjOVo1:-MgBMwGGBfjIYYRjOVo2:bigo0wl) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L355)):*
> ```
>    * Runs a multi-person keypoint model on an image, including input image
>    * padding.
> ```
Perhaps we can drop the information about padding, since this is an internal detail
___
*[pose-detection/src/movenet/detector.ts, line 375 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBNPvaBdImbfHQZzom:-MgBNPvaBdImbfHQZzon:bj7sujy) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L375)):*
> ```
> MOVENET_MULTIPOSE_RESOLUTION * imageSize.height / imageSize.width
> ```
does this need to be rounded?
___
*[pose-detection/src/movenet/detector.ts, line 411 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBPYj14YttLe9HtD7x:-MgBPYj14YttLe9HtD7y:b99eh9p) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L411)):*
> ```
> image coordinates.
> ```
Seems like these are in normalized coordinates
___
*[pose-detection/src/movenet/detector.ts, line 414 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBOzbc5LZrxXKXLw6X:-MgBOzbc5LZrxXKXLw6Y:b8wgwwn) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L414)):*
> ```
> keypoints[i][j].y
> ```
do we need to clip these to [0, 1], or are they clipped elsewhere?


<!-- Sent from Reviewable.io -->

2021-08-03 21:29 UTC, ardoerlemans reviewed
Thanks for the reviews! PTAL.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-:-MgCuy31BL10xMVEHkF4:b7f7qcd)* status: 0 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

___
*[pose-detection/src/movenet/detector.ts, line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8DlF2-gxywxJslT7_:-MgByNJm2E1RmqZU7v3G:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L96)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> const numKeypoints = 17;
> ```
Can you define this const in the constants.ts file?
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 140 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8EekOC1PWglo13ssE:-MgByoHm-PBcpnQRO0iB:bpvdy0r) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L140)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>     if (!this.moveNetModel) {
>       return null;
>     }
> ```
Can this condition happen?
</blockquote></details>

After looking at the tf.loadGraphModel() documentation, it seems that it always return a tf.GraphModel, so this condition will never happen. Removed it.
___
*[pose-detection/src/movenet/detector.ts, line 145 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8Gva7AQV1oTxwbUYj:-MgC-HOZ45dgGlsbKD59:b4kb4n4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L145)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> !outputTensor
> ```
When will this happen?
</blockquote></details>

Great question, I added this to the initial MoveNet code just to make sure we actually received a tensor from the model, but the TF.js API documentation doesn't mention execute() can return null. I have removed this statement.
___
*[pose-detection/src/movenet/detector.ts, line 151 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8EsGW6nOocqBZ_ekf:-MgC-t4854ZqvvExRcTY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L151)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>     const numKeypoints = 17;
>     const boundingBoxSize = 5;  // ymin, xmin, ymax, xmax, score
> ```
Move this two constants to constants.ts
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 154 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8FEIACZy5L8g9OCsC:-MgC-vlg-thBtfC7jQ9P:begu4vo) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L154)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>     if (outputTensor.shape.length !== 3 || outputTensor.shape[0] !== 1 ||
>         outputTensor.shape[2] !== multiPoseInstanceSize) {
> ```
When will this condition happen?
</blockquote></details>

If you load a model that doesn't have the expected output signature, which can happen when you load a model from a URL.
___
*[pose-detection/src/movenet/detector.ts, line 178 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8GKziBXzdRSH98qyW:-MgC07NJAwvjITzk5uJj:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L178)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 3
> ```
Change this to a constant.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKVAQ90IJpMDuMVDw:-MgC16gJEkmhqTSVI8WZ:b-8upw39) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L185)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

Since we have them, shouldn't we store the boxes and box scores as well?
</blockquote></details>

Good point. I have added the box score, but the Pose interface doesn't have bounding box coordinates yet. I'll talk to Na about adding it and updating the API docs.
___
*[pose-detection/src/movenet/detector.ts, line 192 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKf6R9HsKBhi69ufk:-MgC1XNAE9MdYtFRRbka:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L192)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> should
> ```
remove
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 245 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8Gg-m8fJfq5Cv4Ldf:-MgC1bRsAfQD6VVY9s24:b32rvpa) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L245)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> !keypoints
> ```
It seems for singlePose, keypoints will never be falsy. Should you checkout the output of singlePose and set it to `null` instead of `[null]`?
</blockquote></details>

This code has now been updated and the estimate* calls now return a pose or an array of poses, so this check has been removed.
___
*[pose-detection/src/movenet/detector.ts, line 252 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8Hx3C7oc7ThbgcXdB:-MgC2-7T3LZGr0DI_Irv:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L252)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> i
> ```
sugg: poseIdx
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 255 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8HzTx4o10EGGLb9kS:-MgC2-SNEDdvVkDGaXJQ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L255)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> j
> ```
sugg: keypointIdx
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 286 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBMFoc-Sv-NtBGIHFE:-MgC26ZrE0ZFRe6PC66L:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L286)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> *
> ```
Maybe don't add spaces between @params, to be consistent
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 355 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBMwGGBfjIYYRjOVo1:-MgC2CwGDV4mxsgyEd9O:bm0fszu) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L355)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
>    * Runs a multi-person keypoint model on an image, including input image
>    * padding.
> ```
Perhaps we can drop the information about padding, since this is an internal detail
</blockquote></details>

Updated the comment to refer to 'preprocessing'. Let me know if that works for you. My goal was to indicate that this function does more than just run the model, but I agree that the description does not need to include  [...]

2021-08-03 22:49 UTC, ronnyvotel approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-:-MgDCFlQ-C_XMfy9GMMK:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, and @ronnyvotel)

___
*[pose-detection/src/movenet/crop_utils.ts, line 48 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD3nML7f5bKLrSXoIg:-MgD3nML7f5bKLrSXoIh:bpmhy09) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/crop_utils.ts#L48)):*
> ```
> keypoints
> ```
nit: keypoint
___
*[pose-detection/src/movenet/crop_utils.ts, line 104 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD55o55rkZBwm297yg:-MgD55o55rkZBwm297yh:b-d6briz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/crop_utils.ts#L104)):*
> ```
> joints
> ```
nit: joint
___
*[pose-detection/src/movenet/crop_utils.ts, line 177 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD68ig1pLJueZdDxq5:-MgD68ig1pLJueZdDxq6:b-4kzl9t) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/crop_utils.ts#L177)):*
> ```
> quess
> ```
guess
___
*[pose-detection/src/movenet/detector.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKVAQ90IJpMDuMVDw:-MgD8uRX3qS74l4DQXtG:bok4un3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L185)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Good point. I have added the box score, but the Pose interface doesn't have bounding box coordinates yet. I'll talk to Na about adding it and updating the API docs.
</blockquote></details>

Yeah I recommend to just add it (as optional)
___
*[pose-detection/src/movenet/detector.ts, line 355 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBMwGGBfjIYYRjOVo1:-MgDA6zO5wwsKKojYFLi:b-vs1pr4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L355)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Updated the comment to refer to 'preprocessing'. Let me know if that works for you. My goal was to indicate that this function does more than just run the model, but I agree that the description does not need to include details about padding.
</blockquote></details>

Looks good.
___
*[pose-detection/src/movenet/detector.ts, line 134 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD8JA27bObBADIc5rO:-MgD8JA27bObBADIc5rP:b-ifd9x3) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/detector.ts#L134)):*
> ```
> array of
> ```
remove
___
*[pose-detection/src/movenet/detector.ts, line 232 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD9d5xBHPEhlsRma86:-MgD9d5xBHPEhlsRma87:b-yteugh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/detector.ts#L232)):*
> ```
> and calculate the overall pose score
> ```
you can remove this since we no longer do this here
___
*[pose-detection/src/movenet/detector.ts, line 370 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDAersAqVHRyjSwh8_:-MgDAersAqVHRyjSwh8a:b-blfha8) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/detector.ts#L370)):*
> ```
> =
> ```
*= paddedHeight/resizedHeight
___
*[pose-detection/src/movenet/types.ts, line 46 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDCBDd10sKfrAQbyNW:-MgDCBDd10sKfrAQbyNX:b2qt49w) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/types.ts#L46)):*
> ```
>  // TEMP!
> ```
Do you want to just document this above?


<!-- Sent from Reviewable.io -->

2021-08-03 23:45 UTC, ardoerlemans reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @ronnyvotel)

___
*[pose-detection/src/movenet/crop_utils.ts, line 48 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD3nML7f5bKLrSXoIg:-MgDMR3l3aMSXXDJExuO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/crop_utils.ts#L48)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> keypoints
> ```
nit: keypoint
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/crop_utils.ts, line 104 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD55o55rkZBwm297yg:-MgDMVtgDZ2ZeNnEdM7T:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/crop_utils.ts#L104)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> joints
> ```
nit: joint
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/crop_utils.ts, line 177 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD68ig1pLJueZdDxq5:-MgDMZsH6M6fzcsJOI3z:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/crop_utils.ts#L177)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> quess
> ```
guess
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKVAQ90IJpMDuMVDw:-MgDNhKB08zI1LLnTPQH:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L185)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

Yeah I recommend to just add it (as optional)
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 355 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBMwGGBfjIYYRjOVo1:-MgDO-wE-1sL3I7zIvYG:b-ucfkn4) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L355)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

Looks good.
</blockquote></details>

Thanks.
___
*[pose-detection/src/movenet/detector.ts, line 134 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD8JA27bObBADIc5rO:-MgDMhPX8qXKyNeI8Pxf:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/detector.ts#L134)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> array of
> ```
remove
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 232 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgD9d5xBHPEhlsRma86:-MgDNzRb-gsGCelSkIkk:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/detector.ts#L232)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> and calculate the overall pose score
> ```
you can remove this since we no longer do this here
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 370 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDAersAqVHRyjSwh8_:-MgDOC4M0Z0awpVaqvwN:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/detector.ts#L370)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
> =
> ```
*= paddedHeight/resizedHeight
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/types.ts, line 46 at r3](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDCBDd10sKfrAQbyNW:-MgDOEk_AmC6zFOdqXLG:b-29ocz) ([raw file](https://github.com/tensorflow/tfjs-models/blob/db5465be7c5bf590030bb1b0912313184e64ef58/pose-detection/src/movenet/types.ts#L46)):*
<details><summary><i>Previously, ronnyvotel wrote…</i></summary><blockquote>

> ```
>  // TEMP!
> ```
Do you want to just document this above?
</blockquote></details>

Oh, this wasn't supposed to be part of the API just yet. I'll add it later. Removed for now.


<!-- Sent from Reviewable.io -->

2021-08-04 00:10 UTC, lina128 requested changes
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, and @ronnyvotel)

___
*[pose-detection/src/types.ts, line 74 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDSwrVBjNksXEs7xXo:-MgDSwrVBjNksXEs7xXp:bz20tor) ([raw file](https://github.com/tensorflow/tfjs-models/blob/53bf8d9b803507d9839fea7fc0c463f764867a24/pose-detection/src/types.ts#L74)):*
> ```
> box?: BoundingBox;
> ```
Add annotation.
___
*[pose-detection/src/movenet/detector.ts, line 154 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8FEIACZy5L8g9OCsC:-MgDTLLZEgGiHHiLkD5n:b5nw527) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L154)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

If you load a model that doesn't have the expected output signature, which can happen when you load a model from a URL.
</blockquote></details>

Got it, if that's the case, shouldn't we let the pipeline throw error so that users are aware of it instead of swallow it silently.
___
*[pose-detection/src/movenet/detector.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKVAQ90IJpMDuMVDw:-MgDTddn4eTBnRo-mHzy:b32v57) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L185)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

+1
___
*[pose-detection/src/movenet/detector.ts, line 380 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8K6zM4U1WMAPG5NYQ:-MgDUm-g2enBJFLzxJK3:b32w49) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L380)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Because we use a dynamic input shape to our model, we still need to calculate the padded image size (and therefore the resized image size as well), so this can't be reduced to a single line unfortunately. Also, convertImageToTensor does not take a 4D tensor as input, so it would require a bit more work to be able to use convertImageToTensor here. I would like to take a closer look at the output of this function to make sure it meets our needs. I can do that in a follow-up PR.
</blockquote></details>

SG
___
*[pose-detection/src/movenet/detector.ts, line 414 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8MTkSACp4c_gLsvwA:-MgDUnQr30Sj_tXB-HHw:b32w49) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L414)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

As I mentioned above, I'm happy to take a look at this in a follow-up PR because I want to make sure that convertToImageTensor and removeLetterBox meet our needs.
</blockquote></details>

SG
___
*[pose-detection/src/movenet/detector.ts, line 431 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8MuZD8fi1wZWc43oQ:-MgDUpGU-DPhTA0BLLfo:b-ucfknh) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L431)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

I have moved the stateless code to a separate file.
</blockquote></details>

Thanks!
___
*[pose-detection/src/movenet/detector.ts, line 266 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDUFqnAPONSaTd6NRZ:-MgDUFqnAPONSaTd6NR_:b-6m262u) ([raw file](https://github.com/tensorflow/tfjs-models/blob/53bf8d9b803507d9839fea7fc0c463f764867a24/pose-detection/src/movenet/detector.ts#L266)):*
> ```
> null
> ```
Looks like this method will always return a pose, should we remove null here?
___
*[pose-detection/src/movenet/detector.ts, line 295 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDUOOG-JtbNJ8DEuVl:-MgDUOOG-JtbNJ8DEuVm:b-r93lad) ([raw file](https://github.com/tensorflow/tfjs-models/blob/53bf8d9b803507d9839fea7fc0c463f764867a24/pose-detection/src/movenet/detector.ts#L295)):*
> ```
> {keypoints: [], score: 0.0};
> ```
Does it make more sense to return null, because it means no pose is detected. For downstream code, checking `pose == null` is more readable than checking `pose.keypoints.length == 0`


<!-- Sent from Reviewable.io -->

2021-08-04 17:38 UTC, ardoerlemans reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, and @ronnyvotel)

___
*[pose-detection/src/types.ts, line 74 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDSwrVBjNksXEs7xXo:-MgGq-u07CY8v4h5mDGI:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/53bf8d9b803507d9839fea7fc0c463f764867a24/pose-detection/src/types.ts#L74)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> box?: BoundingBox;
> ```
Add annotation.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 154 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-Mg8FEIACZy5L8g9OCsC:-MgGqerP87ON0BxVhvP6:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L154)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Got it, if that's the case, shouldn't we let the pipeline throw error so that users are aware of it instead of swallow it silently.
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgBKVAQ90IJpMDuMVDw:-MgGqjSL4rcS4JrPxS8n:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/d604a7fa46e8f9f2841f7fb3467001aaf8ccf944/pose-detection/src/movenet/detector.ts#L185)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 266 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDUFqnAPONSaTd6NRZ:-MgGreVu1GTzJk7JUIWn:b-896fix) ([raw file](https://github.com/tensorflow/tfjs-models/blob/53bf8d9b803507d9839fea7fc0c463f764867a24/pose-detection/src/movenet/detector.ts#L266)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> null
> ```
Looks like this method will always return a pose, should we remove null here?
</blockquote></details>

Done.
___
*[pose-detection/src/movenet/detector.ts, line 295 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDUOOG-JtbNJ8DEuVl:-MgGre8l3xXxcojHy0ka:b-93mg1l) ([raw file](https://github.com/tensorflow/tfjs-models/blob/53bf8d9b803507d9839fea7fc0c463f764867a24/pose-detection/src/movenet/detector.ts#L295)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> {keypoints: [], score: 0.0};
> ```
Does it make more sense to return null, because it means no pose is detected. For downstream code, checking `pose == null` is more readable than checking `pose.keypoints.length == 0`
</blockquote></details>

Good point. But given that estimatePose() always returns an array of Poses, I have updated this method to do the same thing, so when there's no reliable pose it now returns an empty array.


<!-- Sent from Reviewable.io -->

2021-08-04 18:37 UTC, ardoerlemans reviewed
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, and @ronnyvotel)

___
*[pose-detection/src/movenet/detector.ts, line 295 at r4](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-MgDUOOG-JtbNJ8DEuVl:-MgHS2e4EKEK_19Wxj1B:b50ry8w) ([raw file](https://github.com/tensorflow/tfjs-models/blob/53bf8d9b803507d9839fea7fc0c463f764867a24/pose-detection/src/movenet/detector.ts#L295)):*
<details><summary><i>Previously, ardoerlemans (Ard Oerlemans) wrote…</i></summary><blockquote>

Good point. But given that estimatePose() always returns an array of Poses, I have updated this method to do the same thing, so when there's no reliable pose it now returns an empty array.
</blockquote></details>

That should be 'estimatePoses' that always returns an array of Poses.


<!-- Sent from Reviewable.io -->

2021-08-04 18:56 UTC, lina128 approved these changes
This is great, thank you Ard!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-models/770#-:-MgHWWd99U9to_7ebcEM:b-5j6ioj)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ardoerlemans, @lina128, and @ronnyvotel)



<!-- Sent from Reviewable.io -->

2021-08-04 19:22 UTC, ardoerlemans commented
Thanks!

2021-08-04 19:23 UTC, merged